### ISSUE TITLE
Not every class can be loaded as dependency via maven

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite-testing-frameworks#12]
So, I tried to include this lib via maven in my test project:

```xml
    <dependency>
      <groupId>org.openrewrite.recipe</groupId>
      <artifactId>rewrite-testing-frameworks</artifactId>
      <version>0.5.1</version>
    </dependency>
```

However not every visitor is visible from it:

<img width="558" alt="Screenshot 2020-12-02 at 13 30 53" src="https://user-images.githubusercontent.com/7002896/100854805-8a031d80-349a-11eb-8974-6437e26ab757.png">

I am not sure why...

**Comment by sambsnyd** [comment]
In 0.5.1 that visitor was named ChangeTestAnnotation.
As of the just-released 0.6.0 it has been renamed to UpdateTestAnnotation. 
I don't believe any changes were made to the substance or behavior of the visitor between those versions.
