### ISSUE TITLE
Wrong receiver type on hamcrest method after JUnit 4 -> 5 migration

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite-testing-frameworks#145]
This is run on salesforce/mirus

![image](https://user-images.githubusercontent.com/1697736/121430081-801c1480-c92c-11eb-8974-e0be3a91b9ae.png)

**Comment by sambsnyd** [comment]
For reference, JUnit's Assertions class does not have an `assertThat` method. The appropriate receiver type is `org.hamcrest.MatcherAssert`
