### ISSUE TITLE
Unnecessary dependencies added

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite-testing-frameworks#151]
![image](https://user-images.githubusercontent.com/1697736/122976601-637ad600-d349-11eb-80a1-9044542dac30.png)

**Comment by traceyyoshima** [comment]
Already fixed.
A transitive dependency check was merged to AddDependency on 6.11.
I tested and confirmed the DependencyInsight finds the junit dependencies, and that AddDependency does not add to a pom if they are transitively presenent.

Confirmed by running the latest snapshot of rewrite spring `"JUnit Jupiter for Spring Boot 2.x projects"` and the dependencies are not added.
