### ISSUE TITLE
Hamcrest Assertions -> AssertJ Migration

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-testing-frameworks#16]
Add a recipe to migrate Hamcrest assertions to AssertJ's fluent API. 

#### org.hamcrest.MatcherAssert.assertThat(T , Matcher)

- [ ] org.hamcrest.Matchers.is (Unwrap `is()` from it's nested matcher)
- [ ] org.hamcrest.Matchers.not 
- [ ] org.hamcrest.Matchers.all

Generic matchers

- [ ] org.hamcrest.Matchers.equalTo
- [ ] org.hamcrest.Matchers.nullValue
- [ ] org.hamcrest.Matchers.notNullValue
- [ ] org.hamcrest.Matchers.sameInstance/isA/instanceOf

String matchers

- [ ] org.hamcrest.Matchers.containsString
- [ ] org.hamcrest.Matchers.containsStringIgnoringCase
- [ ] org.hamcrest.Matchers.equalsToIgnoringCase
- [ ] org.hamcrest.Matchers.equalsToIgnoringWhiteSpace
- [ ] org.hamcrest.Matchers.emptyString
- [ ] org.hamcrest.Matchers.emptyORNullString
- [ ] org.hamcrest.Matchers.endsWith
- [ ] org.hamcrest.Matchers.endsWithIgnoringCase
- [ ] org.hamcrest.Matchers.matchesPattern
- [ ] org.hamcrest.Matchers.matchesRegex

Comparables:

- [ ] org.hamcrest.Matchers.lessThan
- [ ] org.hamcrest.Matchers.lessThanOrEqualTo
- [ ] org.hamcrest.Matchers.greaterThan
- [ ] org.hamcrest.Matchers.greathThanOrEqualTo
- [ ] org.hamcrest.Matchers.closeTo()

Arrays/Collections:

- [ ] org.hamcrest.Matchers.contains
- [ ] org.hamcrest.Matchers.in/isIn
- [ ] org.hamcrest.Matchers.isOneOf/oneOf
- [ ] org.hamcrest.Matchers.containsInAnyOrder
- [ ] org.hamcrest.Matchers.contains
- [ ] org.hamcrest.Matchers.hasSize()
- [ ] org.hamcrest.Matchers.hasLength()
- [ ] org.hamcrest.Matchers.arrayWithSize
- [ ] org.hamcrest.Matchers.iterableWithSize

- [ ] org.hamcrest.Matchers.emptyArray
- [ ] org.hamcrest.Matchers.emptyCollectionOf
- [ ] org.hamcrest.Matchers.emptyIteratble
- [ ] org.hamcrest.Matchers.hasItem
- [ ] org.hamcrest.Matchers.hasKey
- [ ] org.hamcrest.Matchers.hasValue

**Comment by sambsnyd** [comment]
We aren't going to tackle this any time soon. The resolution of issue #61 is sufficient until such time as we have a customer or design partner for whom that is insufficient.
