### ISSUE TITLE
Rewrite WireMockRule usage to WireMockExtension

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-testing-frameworks#170]
[As of 2.31.0 WireMock supports JUnit5](http://wiremock.org/docs/junit-jupiter/).
Conversion can [be relatively straightforward](https://github.com/wiremock/wiremock/pull/1616):
```java
    @Rule // com.github.tomakehurst.wiremock.junit.WireMockRule
    public WireMockRule origin = new WireMockRule(options().dynamicHttpPort());
```
becomes:
```java
    @RegisterExtension // com.github.tomakehurst.wiremock.junit5.WireMockExtension
    public WireMockExtension origin = WireMockExtension.newInstance().options(options().dynamicHttpPort()).build();
```
The options passed here are optional, but fit with [typical use](http://wiremock.org/docs/junit-extensions/).

Currently the docs list WireMock as having no JUnit 5 equivalent;
at the very least one could mention conversion is not yet supported.

Ideally conversion would be supported out of the box for the simplest of cases.

**Comment by jkschneider** [comment]
Thanks @timtebeek for bringing this to our attention. I added a recipe for this that handles the case you mentioned above and all the other constructor variants of `WireMockRule` in spite of how uncommon they may be. Will update the docs as well.

**Comment by timtebeek** [comment]
Awesome! Glad to see this added, and a lot quicker than I was expecting. Thanks a lot! :)
