### ISSUE TITLE
Replace Mockito APIs dropped in v4

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-testing-frameworks#173]
[Mockito v4.0.0 drops quite a few older APIs](https://github.com/mockito/mockito/releases/tag/v4.0.0).

An overview of now-deleted classes/methods:

- `org.mockito.Matchers` which was an alias for `org.mockito.ArgumentMatchers`
- `org.mockito.ArgumentMatchers#{anyObject,anyVararg}` both which were aliases for `org.mockito.ArgumentMatchers#any`
- `org.mockito.ArgumentMatchers#any*Of`, which were aliases for the same method name without the Of and the generic parameters (which were ignored)
- `org.mockito.ArgumentMatchers#{is}{Not}Null(Class)` which took a class which was ignored. Aliases for the same methods without the parameter
- `org.mockito.MockedStatic#verify` which had the parameter types reversed
- `org.mockito.Mockito#verifyZeroInteractions` an alias of `verifyNoMoreInteractions`
- `org.mockito.Mockito#debug` framework integration API that we later refactored
- `org.mockito.configuration.AnnotationEngine` which was leaking internal APIs and instead users should use `org.mockito.plugins.AnnotationEngine`
- `org.mockito.exceptions.verification.TooLittleActualInvocations` fixed the grammar from "Little" to "Few"
- Numerous internal APIs that we never officially supported and can now remove
- `org.mockito.plugins.InstantiatorProvider` which was leaking internal APIs and instead users should use `InstantiatorProvider2` (we should probably rename back to remove the number in a future major release)
- `org.mockito.runners` a package that hosted several old JUnit runners which were no longer supported. Users should instead use `org.mockito.junit.MockitoJUnitRunner` which is our official JUnit4 runner.

**Comment by pway99** [comment]
This is very helpful, thanks @timtebeek!
