### ISSUE TITLE
Recipe validation error in org.openrewrite.java.testing.assertj.JUnitToAssertj.recipeList[0]

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite-testing-frameworks#179]
Referenced recipe AssertThrowsToAssertExceptionType doesn't exist: https://github.com/openrewrite/rewrite-testing-frameworks/search?q=AssertThrowsToAssertExceptionType

**Comment by sambsnyd** [comment]
Thanks for reporting!
