### ISSUE TITLE
Rewrite JUnit 3 tests to JUnit 5

### ISSUE THREAD

**Issue by Thihup** [openrewrite/rewrite-testing-frameworks#180]
While trying this project, I've found that some of the tests are using JUnit 3, so they aren't rewritten, causing the build to fail.

A project example: https://github.com/shrinkwrap/shrinkwrap

**Comment by sambsnyd** [comment]
We currently have no plans to automate JUnit 3 upgrade, but we would accept pull requests adding those recipes. 
If you'd like to try authoring JUnit 3 upgrade recipes, I'd be happy to provide guidance on the our [community slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA).
