### ISSUE TITLE
JUnit 4->5 is not migrating Junit 3 assert to junit 5 assert

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-testing-frameworks#190]
![image](https://user-images.githubusercontent.com/1878529/153245838-4870d614-08f3-4b76-8836-287657fa040e.png)

**Comment by timtebeek** [comment]
Likely fix in https://github.com/openrewrite/rewrite-testing-frameworks/pull/256; figured make it part of the existing TestCase migration recipe, so there's no potential for ordering conflicts or anything.
