### ISSUE TITLE
JUnit4to5Migration should map VertxUnitRunner to VertxExtension

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#198]
See : https://stackoverflow.com/questions/55276555/when-to-use-runwith-and-when-extendwith

Example : @RunWith(VertxUnitRunner.class)

**Comment by pway99** [comment]
It looks like the `VertxUnitRunner` can be replaced with the [VertxExtension](https://vertx.io/docs/vertx-junit5/java/)

Have you had a chance to check out the [RunnerToExtension](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/junit5/RunnerToExtension.java) recipe?

**Comment by yeikel** [comment]
> It looks like the `VertxUnitRunner` can be replaced with the [VertxExtension](https://vertx.io/docs/vertx-junit5/java/)
> 
> Have you had a chance to check out the [RunnerToExtension](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/junit5/RunnerToExtension.java) recipe?

I was not aware of this recipe

The main challenge I encountered while running `JUnit4to5Migration` is that it left me with a broken build as  `RunnerToExtension ` is not part of the JUnit4to5Migration

Perhaps `JUnit4to5Migration` should fail with an error if it finds `RunWith` annotation?

**Comment by pway99** [comment]
Yeah, I can appreciate the challenge of a broken build and having to either roll back or manually fix the build.  

> I think that it would be better if it failed with a validation exception asking to configure the [RunnerToExtension](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/junit5/RunnerToExtension.java) recipe if it finds any @RunWith reference as part of the migration

I am thinking it would be difficult to validate `Junit4to5Migration` given the number of potential conversions and that some like `SpringRunnerToSpringExtension` are outside the scope of `rewrite-testing-frameworks`. 

Just thinking out loud... if `JUnit4To5Migration` only removes the JUnit dependency if finally none of the types are in use then the `SpringBoot2JUnit4to5Migration` would also have to remove the JUnit dependency since it might not have been removed via `JUnit4To5Migration`

**Comment by yeikel** [comment]
> Yeah, I can appreciate the challenge of a broken build and having to either roll back or manually fix the build.
> 
> > I think that it would be better if it failed with a validation exception asking to configure the [RunnerToExtension](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/junit5/RunnerToExtension.java) recipe if it finds any @RunWith reference as part of the migration
> 
> I am thinking it would be difficult to validate `Junit4to5Migration` given the number of potential conversions and that some like `SpringRunnerToSpringExtension` are outside the scope of `rewrite-testing-frameworks`.
> 
> Just thinking out loud... if `JUnit4To5Migration` only removes the JUnit dependency if finally none of the types are in use then the `SpringBoot2JUnit4to5Migration` would also have to remove the JUnit dependency since it might not have been removed via `JUnit4To5Migration`

I am sorry for the confusion, the linked example refers to Spring Boot, but this problem with the usage of Extensions is not only applicable to Spring Boot. 

Any user of `Junit4to5Migration` that is in a project that uses `RunWith` will experience this problem

**Comment by pway99** [comment]
> The point that I am trying to make is that if Junit4to5Migration finds the usage of extensions with the RunWith syntax (Junit4),if should fail and instruct the user to also configure RunnerToExtension for a successful migration to 

I may be misunderstanding your point...  My concern is that if `JUnit4to5Migration` fails on an unsupported `Runner` conversion then `SpringBoot2JUnit4to5Migration` would never succeed since the `SpringRunnerToSpringExtension` is in the rewrite-spring project.

Please note that I refer to `rewrite-spring` because it provides an example of a `RunnerToExtension` recipe that is unknown to `rewrite-testing-frameworks`.

Can you provide a list of the `Runners` needing conversion? Perhaps we can just add them to the Junit migration

**Comment by yeikel** [comment]
> > The point that I am trying to make is that if Junit4to5Migration finds the usage of extensions with the RunWith syntax (Junit4),if should fail and instruct the user to also configure RunnerToExtension for a successful migration to
> 
> I may be misunderstanding your point... My concern is that if `JUnit4to5Migration` fails on an unsupported `Runner` conversion then `SpringBoot2JUnit4to5Migration` would never succeed since the `SpringRunnerToSpringExtension` is in the rewrite-spring project.
> 
> Please note that I refer to `rewrite-spring` because it provides an example of a `RunnerToExtension` recipe that is unknown to `rewrite-testing-frameworks`.
> 
> Can you provide a list of the `Runners` needing conversion? Perhaps we can just add them to the Junit migration

I understand

I think that it'll be hard to give you a list because there are hundreds of extensions

**Comment by yeikel** [comment]
Maybe we can start and add as we receive feedback? 

For example : 

`RunWith(VertxUnitRunner.class) -> @ExtendWith(VertxExtension.class)`

**Comment by pway99** [comment]
That sounds fantastic,  thanks!

**Comment by pway99** [comment]
@yeikel my apologies for closing the issue via the commit adding the VertxUnitRunner -> VertxExtension recipe.
I just added https://github.com/openrewrite/rewrite-testing-frameworks/issues/199 for gathering feedback and tracking new aditions

**Comment by yeikel** [comment]
> @yeikel my apologies for closing the issue via the commit adding the VertxUnitRunner -> VertxExtension recipe. I just added #199 for gathering feedback and tracking new aditions

No problem. Thank you for the quick responses

We can probably close this at this point and move the suggestions to #199

**Comment by tkvangorder** [comment]
I am going to scope this issue to the immediate fix (adding a mapping from the VertxRunner to the VertxExtension) and will close this issue. Any future places we run into library-specific runner->mapper issues, we can address those as they happen.

@yeikel thanks for reporting!
