### ISSUE TITLE
JUnit Runner To Jupiter Extension recipes

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#199]
This task is for suggesting and keeping track of JUnit 4 to Jupiter 5 Runner to Extension Recipes

**Comment by pway99** [comment]
RunWith(VertxUnitRunner.class) -> @ExtendWith(VertxExtension.class)

**Comment by tkvangorder** [comment]
@pway99 I am going to close this issue out, as we can deal we each "runner to extension" ad hoc, as they are reported as issues.
