### ISSUE TITLE
Add rule to transform assertEquals(a, null) to assertNull(a)

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#200]
This could be a good transformation to add  : 

`assertEquals(a, null)`

Could be replaced with `assertNull(a)`

Example : 

```
@Test
void myTest(){

String a = null;
assertEquals(a, null);

}
```

```
@Test
void myTest(){

String a = null;
assertNull(a);
}
```

**Comment by jkschneider** [comment]
Good idea!

**Comment by yeikel** [comment]
> Good idea!

Thank you for the quick turnaround!

**Comment by jkschneider** [comment]
In open source code we have already, found a few occurrences of this. https://app.moderne.io/recipes/org.openrewrite.java.testing.cleanup.AssertEqualsNullToAssertNull

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/1697736/160741062-ee3f1235-83b2-44e2-afed-1c81b96a9745.png">

**Comment by yeikel** [comment]
> In open source code we have already, found a few occurrences of this. https://app.moderne.io/recipes/org.openrewrite.java.testing.cleanup.AssertEqualsNullToAssertNull
> 
> <img alt="image" width="1243" src="https://user-images.githubusercontent.com/1697736/160741062-ee3f1235-83b2-44e2-afed-1c81b96a9745.png">

That's awesome. Thank you for sharing about it

I have seen this within my projects as well and I am looking forward to test it

**Comment by yeikel** [comment]
@jkschneider I forgot to mention it with the original issue, but the same applies to assertNotNull. I can create a separate issue if you prefer that 



@Test
void myTest(){

String a = null;
assertNotEquals(a, null);

}

@Test
void myTest(){

String a = null;
assertNotNull(a);
}
