### ISSUE TITLE
org.openrewrite.java.testing.cleanup.BestPractices does not detect assertion in utility method and wraps test around assertDoesNotThrow 

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#201]
While running the recipe `org.openrewrite.java.testing.cleanup.BestPractices`, I bumped into a situation where the rule wraps my code around `assertDoesNotThrow` because it is not able to detect the assertion in one of the utility methods. 

Before  : 

```java
@Test
    public void test1() {
        Set<String> s = Set.of("hello");
        testContains(s, "hello");
    }

@Test
    public void test2() {
        Set<String> s = Set.of("ABC");
        testContains(s, "hello");
    }

private static void testContains(Set<String> set,String word){

assertTrue(set.contains(word));  // It is not able to detect that the assertion is outside the test in this utility function
}
```

After : 

```java
   @Test
    public void test1() {
        assertDoesNotThrow(() -> {
            Set<String> s = Set.of("hello");
            testContains(s, "hello");
        });
    }

    @Test
    public void test2() {
        assertDoesNotThrow(() -> {
            Set<String> s = Set.of("ABC");
            testContains(s, "hello");
        });
    }


```

**Comment by tkvangorder** [comment]
@yeikel Thank you for reporting.

The problem is that we have no way of really knowing if a method invocation's body includes assertions. We could attempt to use a visitor to create a list of all methods (that do not have a test annotation) that do include an assertion, but that would only work if the assertions are in the same project. Any external referenced methods would be a black box to this visitor.

How about if we added configuration to allow the user to define additional packages, classes, or method names that are detected as "assert-enabled"? 

So in addition [to this list](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertions.java#L41-L53), there would also be an "additionalAsserts" to allow customization.

**Comment by yeikel** [comment]
@tkvangorder Can we do both? 

1. Check within the class (or project if possible) for the method calls to check for the assertions

Generally, In my personal experience I have only seen this within the same project, but it is definitely possible to import this externally

3. Provide a way to customize as you mentioned

**Comment by yeikel** [comment]
> Hi @yeikel, I've started to take a look at the issue and would like to check on a small detail.
> 
> Is the `@Test` annotation from `org.junit.jupiter.api.Test`?

Yes

**Comment by traceyyoshima** [comment]
@yeikel the recipe will detect methods with assertions in the test body that exists in the same class.

Detecting methods in the same project that contain an assertion could be pretty tricky and possibly inaccurate.
So, instead, I added @tkvangorder 's suggestion for optional additional asserts.
The option is a comma-delimited String that will allow methods references from things like common test utilities to be considered a valid assertion to prevent wrapping.

Please let me know if you have any questions.

**Comment by yeikel** [comment]
> @yeikel the recipe will detect methods with assertions in the test body that exists in the same class.
> 
> Detecting methods in the same project that contain an assertion could be pretty tricky and possibly inaccurate.
> So, instead, I added @tkvangorder 's suggestion for optional additional asserts.
> The option is a comma-delimited String that will allow methods references from things like common test utilities to be considered a valid assertion to prevent wrapping.
> 
> Please let me know if you have any questions.

Thank you. I think that this should do it for now

Will this also detect assertions in parent classes or strictly within the same class?

**Comment by traceyyoshima** [comment]
> Will this also detect assertions in parent classes or strictly within the same class?

The automation is limited to the same class.
I think checking each class's parent class for possible assertions may be unnecessary most of the time. So, the `additionalAsserts` is meant to fill in those gaps.
So, the optional parameter is meant to cover those types of cases.

**Comment by yeikel** [comment]
> > Will this also detect assertions in parent classes or strictly within the same class?
> 
> The automation is limited to the same class.
> I think checking each class's parent class for possible assertions may be unnecessary most of the time. So, the `additionalAsserts` is meant to fill in those gaps.
> So, the optional parameter is meant to cover those types of cases.

Is there any type checking for these additional methods? And also, how will it look like in yaml?

**Comment by traceyyoshima** [comment]
> Is there any type checking for these additional methods? And also, how will it look like in yaml?

Yes, it works the same way as the [default list](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertions.java#L42).

The method needs to [start with](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertions.java#L236) what's specified in the list.

Specifying parameters works like any recipe with [options](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertions.java#L61). So, in this case:
- org.openrewrite.java.testing.cleanup.TestsShouldIncludeAssertions:
    additionalAsserts: "org.foo"
