### ISSUE TITLE
Recipe to transform  assertTrue(a == b) to assertEquals(a,b)

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#204]
Example : 

Before : 

```java

@Test
void myTest(){

String a = null;
String b = null;

assertTrue(a == b);

}
```

After : 

```java


@Test
void myTest(){

String a = null;
String b = null;

assertEquals(a,b)
}
```

**Comment by pway99** [comment]
good suggestion!

just a tip, when you have a chance check out how github [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) improves code blocks

**Comment by yeikel** [comment]
> good suggestion!
> 
> just a tip, when you have a chance check out how github [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) improves code blocks

Thank you for the suggestion. I updated it
