### ISSUE TITLE
java:S5786 : JUnit 5 test classes and methods should have default package visibility

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#210]
Before : 

```java

import org.junit.jupiter.api.Test;

public class MyClassTest { // Noncompliant - modifier can be removed
  @Test
  protected void test() { // Noncompliant - modifier can be removed
    // ...
  }
}
```

```java

import org.junit.jupiter.api.Test;

class MyClassTest {
  @Test
  void test() {
    // ...
  }
}

````

Read more : https://rules.sonarsource.com/java/RSPEC-5786/

Also : https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods

**Comment by pway99** [comment]
Hi @yeikel and thanks for identifying this issue.
This looks like a case where `SonarSource` may be out of sync with `Junit` and the `TestsShouldNotBePublic` recipe strictly conforms to the JUnit spec.  

[TestsShouldNotBePublic](https://github.com/openrewrite/rewrite-testing-frameworks/blob/171d1bec22f7029119c5d931b62b8ae69e3e84bf/src/test/kotlin/org/openrewrite/java/testing/cleanup/TestsShouldNotBePublicTest.kt#L275-L306) ignores `protected` modifiers

Junit docs:
> Class and method visibility
Test classes, test methods, and lifecycle methods are not required to be public, but they must not be private.

SonarSource
> JUnit5 test classes can have any visibility but private, however, it is recommended to use the default package visibility, which improves readability of code.

**Comment by yeikel** [comment]
> Hi @yeikel and thanks for identifying this issue.
> This looks like a case where `SonarSource` may be out of sync with `Junit` and the `TestsShouldNotBePublic` recipe strictly conforms to the JUnit spec.  
> 
> [TestsShouldNotBePublic](https://github.com/openrewrite/rewrite-testing-frameworks/blob/171d1bec22f7029119c5d931b62b8ae69e3e84bf/src/test/kotlin/org/openrewrite/java/testing/cleanup/TestsShouldNotBePublicTest.kt#L275-L306) ignores `protected` modifiers
> 
> Junit docs:
> > Class and method visibility
> Test classes, test methods, and lifecycle methods are not required to be public, but they must not be private.
> 
> SonarSource
> > JUnit5 test classes can have any visibility but private, however, it is recommended to use the default package visibility, which improves readability of code.
> 

I think we could add one recipe to set them to modifier

This seems to be the preference of IDEA's inspections

**Comment by pway99** [comment]
How about adding an option to the existing recipe?

**Comment by yeikel** [comment]
> How about adding an option to the existing recipe?

That works too
