### ISSUE TITLE
Migrate Cucumber from Junit 4 to Junit 5

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#213]
See : https://github.com/cucumber/cucumber-jvm/issues/1149#issuecomment-611716745

**Comment by timtebeek** [comment]
Might be good to tag onto this that there have been a few iterations on how to run Cucumber with JUnit 5;
[the latest recommended option](https://github.com/cucumber/cucumber-jvm/pull/2362) is using `@Suite` from JUnit 5.8.

**Comment by timtebeek** [comment]
@yeikel With cucumber migration recipes about to move to https://github.com/cucumber/cucumber-jvm-migration, would you feel it's worthwhile to recreate this issue there? It does not seem possible to move issues between organizations.

**Comment by yeikel** [comment]
I created https://github.com/cucumber/cucumber-jvm-migration/issues/4 @timtebeek

**Comment by timtebeek** [comment]
Thanks!
