### ISSUE TITLE
RSPEC-3658:Unit tests should throw exceptions

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#216]
See https://rules.sonarsource.com/java/tag/junit/RSPEC-3658

**Comment by tkvangorder** [comment]
For those contributors that are new to OpenRewrite, please note that there are two additional things to be added to the cleanup recipes: 

Override the time estimate for the issue (per occurrence)

```
    @Override
    public @Nullable Duration getEstimatedEffortPerOccurrence() {
        return Duration.ofMinutes(n);
    }
```

Make sure to label the recipe with the RSPEC number: 
    
```
    @Override
    public Set<String> getTags() {
        return Collections.singleton("RSPEC-3658");
    }

```
