### ISSUE TITLE
Remove empty tests without comments

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#219]
Tests without body or assertions should be removed : 

Before : 

```java

@Test
void test1(){

}

@Test
void test2(){

}

@Test
void test3(){
 // Some comment
}
```

After : 

```java

@Test
void test3(){
 // Some comment
}
```

This is similar to : [#1593](https://github.com/openrewrite/rewrite/issues/1593). The only difference is that there are no exceptions here. I am not sure if this should be the same issue or not

**Comment by tkvangorder** [comment]
This seems like a much safer transformation, if there is a method annotated with `@Test` and the body is empty, remove it.

Test methods with just comments should NOT be removed (as these could likely be commented out tests)
