### ISSUE TITLE
@RunWith(MockitoJUnitRunner.Silent.class) does not migrate to JUnit5

### ISSUE THREAD

**Issue by dianamaesan** [openrewrite/rewrite-testing-frameworks#222]
Hello!

The execution of the recipe **JUnit4to5Migration** does not migrate `@RunWith(MockitoJUnitRunner.Silent.class)`  
 and is not documented at https://docs.openrewrite.org/tutorials/migrate-from-junit-4-to-junit-5#known-limitations.

I have created an example to show you. https://github.com/josemariavillar/test_project/tree/error_migrate_junit5

Thanks in advance.

**Comment by pway99** [comment]
A few notes and a proposed solution for migrating `@RunWith(MockitoJUnitRunner.Silent.class)`

MockitoExtension [strictness](https://github.com/mockito/mockito/blob/737f0a3517256af6ade37fd0e776a2bb230de553/subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java#L53-L57) configuration.
[MockitoSettings](https://github.com/mockito/mockito/blob/main/subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoSettings.java)
[Strictness](https://github.com/mockito/mockito/blob/main/src/main/java/org/mockito/quality/Strictness.java)
[MockitoJunitRunner.Silent](https://github.com/mockito/mockito/blob/737f0a3517256af6ade37fd0e776a2bb230de553/src/main/java/org/mockito/junit/MockitoJUnitRunner.java#L78-L106)

before:
```java
@RunWith(MockitoJUnitRunner.Silent.class)
public class ExternalAPIServiceTest {
...
}
```
after:
```java
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
public class ExternalAPIServiceTest {
...
}
```
