### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by dianamaesan** [openrewrite/rewrite-testing-frameworks#223]
Executing recipe **JUnit4to5Migration** migrate correctly

```
 public WireMockRule solicitudes = new WireMockRule(8082);
```
to 

```
public WireMockExtension solicitudes = WireMockExtension.newInstance().options(WireMockConfiguration.options().port(8082)).build();
```
but it seems that not add the required dependency to the pom.

I have created an example [here](https://github.com/josemariavillar/test_project/tree/error_migrate_junit5).

Thanks in advance.

**Comment by pway99** [comment]
fixed by https://github.com/openrewrite/rewrite-testing-frameworks/commit/be8d8d6e8816bd12a437de45cd4979fed2e3aa97
