### ISSUE TITLE
Strip `test` prefix from test method names

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-testing-frameworks#237]
Inspired by [this thread](https://twitter.com/maciejwalkowiak/status/1549332873219657730)
> Don't use "test" prefix for test methods. This had to be done in JUnit 3 (!) but now it only adds noise. Instead use method names that express the intent.

Seems to me OpenRewrite would be well suited to strip that prefix, and it should nudge developers to rethink their test method naming strategy going forward.

Some things to consider:
1. remove `test` prefix only where (meta) annotated with `@Test`, `@ParameterizedTest` or `@RepeatedTest` (or other `@TestTemplate` annotations
2. probably lowercase the first character after `test` prefix
3. Handle edge cases such as `@Test void test1() {...}` and `@Test void test() {...}` correctly

**Comment by pway99** [comment]
fixed by #240
