### ISSUE TITLE
Wrong rewriting for Arrays.equals 

### ISSUE THREAD

**Issue by clesaec** [openrewrite/rewrite-testing-frameworks#238]
Trying this
```sh
mvn org.openrewrite.maven:rewrite-maven-plugin:4.27.0:run \
    -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:1.24.0 \
    -DactiveRecipes=org.openrewrite.java.testing.junit5.JUnit5BestPractices
```
made this transformation : 
```
-    assertTrue(Arrays.equals(customSyncFile, sameCustomSyncFile));
+    assertEquals(Arrays, customSyncFile);
```

And i still have 
```java
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
```

**Comment by timtebeek** [comment]
For a bit of background; this came out of work on https://github.com/apache/avro/pull/1769. 

Seems there might be some slight issues with the recipe for [parameterized tests migration](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java#L54) and [assertTrue(a.equals(b)) migration](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueEqualsToAssertEquals.java#L35).
