### ISSUE TITLE
Use RemoveImport rather than OrderImports in CleanupJUnitImports

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite-testing-frameworks#24]
Otherwise, sorting only is possible, as shown in the following example from Netflix/eureka. Might have to go improve `RemoveImport` to accept removal of _packages_ rather than just types.

![image](https://user-images.githubusercontent.com/1697736/102391104-1d078180-3f8a-11eb-80d4-fdea7d5c4e3f.png)

**Comment by pway99** [comment]
Reopening since it is affecting SpringBoot Upgrades and JUnit4To5 migration.
per discussion with @sambsnyd 
```
No call to OrderImports, no call to RemoveUnused imports
Honestly removing line 81 doAfterVisit(new OrderImports(false)); and updating tests might be all you have to do
Maybe also AutoFormat the surviving imports so they don't have extra blank lines
```
