### ISSUE TITLE
RemoveTestPrefix recipe must not rename methods to Java keywords

### ISSUE THREAD

**Issue by sbrannen** [openrewrite/rewrite-testing-frameworks#243]
## Overview

I have not personally used the `RemoveTestPrefix` recipe; however, I have implemented the same feature in the past. Thus, I noticed that there appears to be a bug in the implementation.

Specifically, removal of a `test` prefix must not be performed if the remainder of the method name (when de-capitalized) results in a Java keyword.

For example, `testNull()` cannot be renamed to `null()`.

## Related Issues

- #240

**Comment by sbrannen** [comment]
Side notes:

- the recipe should support `org.junit.jupiter.api.TestTemplate`
- the recipe should support JUnit Jupiter test method annotations when used as meta-annotations
  - or does `MethodDeclaration#getLeadingAnnotations` find meta-annotations?

**Comment by timtebeek** [comment]
Thanks for those insights! Hopefully all resolved in #244.

**Comment by jkschneider** [comment]
Thanks for pointing this out @sbrannen and the quick fix @timtebeek !

**Comment by sbrannen** [comment]
> - the recipe should support JUnit Jupiter test method annotations when used as meta-annotations
> 
>     - or does `MethodDeclaration#getLeadingAnnotations` find meta-annotations?

@jkschneider, can you answer that?

**Comment by timtebeek** [comment]
Figured chime back in; I don't know too much about the internals around annotation handling (yet), but figured I could probably work this out by [adding a new test](https://github.com/openrewrite/rewrite-testing-frameworks/compare/main...timtebeek:support_test_meta_annotations). It seems test meta-annotations are not yet supported with the [current use of `TypeUtils` in `hasJUnit5MethodAnnotation`](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/cleanup/RemoveTestPrefix.java#L129).
```java
private static boolean hasJUnit5MethodAnnotation(MethodDeclaration method) {
  for (J.Annotation a : method.getLeadingAnnotations()) {
    if (TypeUtils.isOfClassType(a.getType(), "org.junit.jupiter.api.Test")
```
I also don't yet see a way to get meta-annotations from a `J.Annotation` instance, but I might be lacking some knowledge here.
I do think not yet picking up on meta-annotations might be more widespread through rewrite-testing-frameworks. Not sure what the best way forward would be, but hopefully Jonathan or someone else can provide some guidance.

**Comment by sbrannen** [comment]
@timtebeek, thanks for looking into the meta-annotation support question.

It sounds like it would be worth it to open a dedicated issue for that topic.

@jkschneider?
