### ISSUE TITLE
ExpectedExceptionToAssertThrows does not refact @Test annotation with expected attribute

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite-testing-frameworks#261]
When i want to use the recipe org.openrewrite.java.testing.junit5.ExpectedExceptionToAssertThrows , the refacto on

`@Test(expected = MyException.class)`

does not works.

Is-it possible to delete  the attibute and replace it by the body 

`Assertions.assertThrows`

**Comment by timtebeek** [comment]
I've seen this working in the past; do you have any more details on how you're running OpenRewrite, and which version?
Or even a minimal sample repository to reproduce the issue?

**Comment by jdelobel** [comment]
> I've seen this working in the past; do you have any more details on how you're running OpenRewrite, and which version? Or even a minimal sample repository to reproduce the issue?

HI,

I use all these versions:

Open Rewrite maven plugin 4.33.0
Open Rewrite java version 1.10.0
Open rewrite tesing 1.27.0

In the source code, i found the following test class:

https://github.com/openrewrite/rewrite-testing-frameworks/blob/c98b11e31379ec74235a7105f8aab0738f2e76eb/src/test/kotlin/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.kt

but i dont see a test case for my use case. I dont think this feature is implemented
