### ISSUE TITLE
Heuristically swap expected/actual argument order

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-testing-frameworks#275]
Identified after applying [JUnit5 CleanupAssertions](https://docs.openrewrite.org/reference/recipes/java/testing/junit5/cleanupassertions) on [Apache Wicket](https://github.com/apache/wicket/pull/545#discussion_r1001574012).

Sometimes imperfect migrations result in an incorrect argument order, such as with:
```diff
- assertTrue(fieldBeansCollector.getFieldType() == FieldType.LIST);
+ assertEquals(fieldBeansCollector.getFieldType(), FieldType.LIST);
```
Here the left argument and right argument are ideally swapped, to conform to the expected first, and actual second order.
While this could be fixed individually in [AssertTrueEqualsToAssertEquals](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueEqualsToAssertEquals.java), we can also add a new recipe to swap argument orders based on heuristics. I'm thinking a set of rules such as:

If either argument is the only literal/constant, place that argument first.
if either argument is the only method call, place that argument second.
If either argument named contained expect or actual, place respectively.
...

But there's a number of challenges as well; or risks in getting the order swap wrong:

Imperfect when using something like `createExpectedObject()`.
Should not inadvertently swap String message argument around.

Ideally we only swap arguments when we have a strong indication that a swap improves the test, so any feedback on these heuristics would help. And would you all prefer an isolated fix to CleanupAssertions, or a new recipe that swaps the argument order and can be applied separately?

**Comment by tkvangorder** [comment]
We actually had a design partner report this as a sonar rule (S3415). I think it makes more sense to build a dedicated recipe to address swapping the assertion arguments. 

We can model the logic after what is done in Sonar:

https://github.com/SonarSource/sonar-java/blob/cbf1e883e99c0c54b499b8663543fc6449aa856e/java-checks/src/main/java/org/sonar/java/checks/tests/AssertionArgumentOrderCheck.java

**Comment by pway99** [comment]
completed via https://github.com/openrewrite/rewrite-testing-frameworks/pull/277
