### ISSUE TITLE
Error in Recipe  UpdateTestAnnotation  printed in all pom.xml

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite-testing-frameworks#285]
Hi,

I found this error in all pom.xml in my project when i upgrade from 1.30.0 to 1.31.0 

(Recipe applicable test failed with an exception.
java.lang.IllegalAccessError: tried to access method org.openrewrite.java.search.FindImports.getVisitor()Lorg/openrewrite/java/JavaIsoVisitor; from class org.openrewrite.java.testing.junit5.UpdateTestAnnotation
  org.openrewrite.java.testing.junit5.UpdateTestAnnotation.getSingleSourceApplicableTest(UpdateTestAnnotation.java:49))

**Comment by tkvangorder** [comment]
Hi @jdelobel ,

What version of the `rewrite-maven-plugin` are you using? Is it `4.37.0`?
Can you provide the snippet you are using to apply the rewrite-maven-plugin? (Including the dependency on `rewrite-testing-frameworks`)? 

Thank you!

**Comment by jdelobel** [comment]
> rewrite-maven-plug

Hi,

I use the 4.36.0 for the plugin (I have another problem with the latest version cf https://github.com/openrewrite/rewrite-maven-plugin/issues/443). Sorry this is a large project. I have to take a time to do the snippet but at this time i dont have time

**Comment by tkvangorder** [comment]
@jdelobel Just checking in to see if this is still an issue you are experiencing.  I suspect this is just a mismatch in rewrite versions between the plugin and the rewrite-testing-framework. 

If you are using `rewrite-maven-plugin:4.37.0` then you will want to use `rewrite-testing-framework:1.31.0`

**Comment by timtebeek** [comment]
Given that we've had quite a few new releases since I propose we close this one,
and only reopen if the problem persists after upgrading as tracked in https://github.com/openrewrite/rewrite-maven-plugin/issues/443 .
