### ISSUE TITLE
JUnitToAssertj is not woking

### ISSUE THREAD

**Issue by crehn** [openrewrite/rewrite-testing-frameworks#291]
Checkout Pet Clinic and run
```
mvn org.openrewrite.maven:rewrite-maven-plugin:4.38.0:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:1.31.0 \
  -DactiveRecipes=org.openrewrite.java.testing.assertj.JUnitToAssertj
```

No files are changed although assertEquals is used multiple times.

**Comment by traceyyoshima** [comment]
Hi @crehn, thank you for reporting the issue! We'll take a look

**Comment by traceyyoshima** [comment]
Hi @crehn, I took a look at the [JUnitToAssertJ](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/resources/META-INF/rewrite/assertj.yml#L46) recipe and it seems to be working.

The recipe converts types from `org.junit.jupiter.api.Assertions` to `org.assertj.core.api.Assertions`. And `org.junit.jupiter.api.Assertions` don't exist in the project, which results in no changes.

Please run `org.openrewrite.java.testing.junit5.JUnit4to5Migration` if you'd like to test a JUnit migration instead.

Does this resolve your issue? :)

**Comment by crehn** [comment]
Ah, I see! My bad. Thanks a lot for this fast and helpful answer!

Maybe this information could be added to the recipe description.
