### ISSUE TITLE
Recipe - Replace PowerMockito with raw Mockito

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite-testing-frameworks#293]
Many apps in the wild use PowerMockito to provide static mocking capabilities to Mockito in JUnit 4. 
https://github.com/powermock/powermock/wiki/Mockito

But, Mockito 3.4.0+ can mock statics natively:
https://www.baeldung.com/mockito-mock-static-methods
And PowerMock does not have a version compatible with JUnit 5 (and perhaps never will):
https://github.com/powermock/powermock/issues/929

Developers would likely benefit from a recipe which takes an app using Powermock+Mockito and ~~burns all of the static mocking to the ground~~ replaces usages of PowerMock with equivalent Mockito native syntax (this new recipe could also be called from the JUnit5 recipe)

**Comment by tkvangorder** [comment]
It would be helpful to have specific examples of the PowerMock API and then an equivalent in Mockito 3.4+.

**Comment by klauerm** [comment]
I've recently migrated a huge code base from Mockito 1 to Mockito 4. Unfortunately some migrated modules are using PowerMockito to mock static methods. Those tests are failing after the migration. We urgently need such a recipe. So I've forked this repository and try to write it on my own. I will raise a pull request as soon as I'm finished.

**Comment by klauerm** [comment]
Hi @tkvangorder,
I've drafted the first example what the recipe shall do in a unit test. I've also tried to do some changes by using existing recipes (see mockito.yml) but these are not working.

**Comment by klauerm** [comment]
Continue development in PR  #312 . The integration test src/test/java/org/openrewrite/java/testing/mockito/ReplacePowerMockitoIntegrationTest.java holds all the requirements for the recipe. Can someone please look over and see if something is missing.
