### ISSUE TITLE
`TestsShouldNotBePublic` should not reduce visibility if test classes are extended

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-testing-frameworks#309]
[TestsShouldNotBePublic](https://github.com/openrewrite/rewrite-testing-frameworks/blob/v1.33.0/src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldNotBePublic.java) should not reduce visibility of classes used in subsequent test classes, even if those are in Groovy. As seen in https://github.com/openrewrite/rewrite/pull/2800.

> Compilation fails as JavaTypeSignatureBuilderTest and JavaTypeMappingTest should not have reduced visibility for Groovy.
```
/home/tim/Documents/workspace/rewrite/rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyTypeSignatureBuilderTest.java:24: error: JavaTypeSignatureBuilderTest is not public in org.openrewrite.java; cannot be accessed from outside package
import org.openrewrite.java.JavaTypeSignatureBuilderTest;
                           ^
/home/tim/Documents/workspace/rewrite/rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyTypeSignatureBuilderTest.java:35: error: JavaTypeSignatureBuilderTest is not public in org.openrewrite.java; cannot be accessed from outside package
public class GroovyTypeSignatureBuilderTest implements JavaTypeSignatureBuilderTest {
                                                       ^
/home/tim/Documents/workspace/rewrite/rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyTypeMappingTest.java:23: error: JavaTypeMappingTest is not public in org.openrewrite.java; cannot be accessed from outside package
import org.openrewrite.java.JavaTypeMappingTest;
                           ^
/home/tim/Documents/workspace/rewrite/rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyTypeMappingTest.java:34: error: JavaTypeMappingTest is not public in org.openrewrite.java; cannot be accessed from outside package
class GroovyTypeMappingTest implements JavaTypeMappingTest {
                                       ^
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
4 errors
4 warnings
```

Might be fairly niche; as such I would not consider it high priority for now.

**Comment by timtebeek** [comment]
Also occurs for Java classes that are extended: https://github.com/openrewrite/rewrite-kubernetes/pull/41

**Comment by timtebeek** [comment]
And also for method access in GradleWrapperTest: https://github.com/openrewrite/rewrite/pull/2948

**Comment by mkonietzka** [comment]
Reducing visibilty also breaks constructs like

```
import com.example.SomeGatewayIT;

import org.junit.platform.suite.api.SelectClasses;
import org.junit.platform.suite.api.Suite;

@Suite
@SelectClasses({SomeGatewayIT.class})
public class BranchITSuite {
}
```
SomeGatewayIT cannot be referenced when it becomes non public.

**Comment by timo-abele** [comment]
I think I found another one, someone called their `@AfterEach` annotated method "`finalize`", (unwittingly?) overriding `Object.finalize`. As overriding must not reduce visibility, this breaks the build.

**Comment by timtebeek** [comment]
Thanks for the helpful runnable test; I've created this PR which addresses the issue and welcome a review
- https://github.com/openrewrite/rewrite-testing-frameworks/pull/524

**Comment by mbruggmann** [comment]
@timtebeek Awesome, that looks like a good fix, thanks for implementing it 🎉
