### ISSUE TITLE
`TemporaryFolderToTempDir` breaks when `newFolder()` is part of a chained call

### ISSUE THREAD

**Issue by MrThaler** [openrewrite/rewrite-testing-frameworks#311]
When having a `TemporaryFolder`, the rule correctly replaces all simple calls to `TemporaryFolder::newFolder()` by a new static method meant to create new folders. However, this breaks in chained calls. 
Consider these two methods:

```java
public class TempDirTest
{
  @Rule
  public TemporaryFolder folder = new TemporaryFolder();

  @Test
  public void testFile() throws IOException
  {
    File newFolder = folder.newFolder();
    assertTrue(newFolder.exists());
  }

  @Test
  public void testPath() throws IOException
  {
    Path newFolder = folder.newFolder()
        .toPath();
    assertTrue(Files.exists(newFolder));
  }
}
```
In both of these cases, `TemporaryFolder::newFolder()` should be replaced by a call to the newly created method. However, what actually happens is this:
```java
public class TempDirTest
{

  @TempDir
  public File folder;

  @Test
  void testFile() throws IOException
  {
    File newFolder = newFolder(folder, "junit");
    assertTrue(newFolder.exists());
  }

  @Test
  void testPath() throws IOException
  {
    Path newFolder = folder.newFolder()
        .toPath();
    assertTrue(Files.exists(newFolder));
  }

  private static File newFolder(File root, String... subDirs) throws IOException {
    String subFolder = String.join("/", subDirs);
    File result = new File(root, subFolder);
    if (!result.mkdirs()) {
      throw new IOException("Couldn't create folders " + root);
    }
    return result;
  }
}
```
This leads to a compiler error because the method `testPath()` attempts to call `File::newFolder`...which is not a method that exists.

**Comment by timtebeek** [comment]
Thanks for the detailed report @MrThaler ! I've added this to the backlog, but anyone is welcome to pick this up.

For reference: we already have [three unit tests specifically for `newFolder`](https://github.com/openrewrite/rewrite-testing-frameworks/blob/v1.33.0/src/test/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDirTest.java#L249), the sample you have provided could be a fourth, ideally minimized only to the chained call case. Once the tests are added, the actual code changes will likely go into [AddNewFolderMethod](https://github.com/openrewrite/rewrite-testing-frameworks/blob/v1.33.0/src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java#L145).
