### ISSUE TITLE
Remove duplicates uses of `@TestTemplate` implementations for a single method

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#314]
See: https://github.com/junit-team/junit5/issues/1224

```java
    @Test
    @RepeatedTest(3)
    @DisplayName("When an entry does not exist, it should be created and initialized to 0")
```

```diff



-- @Test
    @RepeatedTest(3)
    @DisplayName("When an entry does not exist, it should be created and initialized to 0")
```

**Comment by timtebeek** [comment]
Related to, but different from https://github.com/openrewrite/rewrite-testing-frameworks/issues/208 ; could be worth to explore one after the other.

**Comment by timtebeek** [comment]
Fixed in https://github.com/openrewrite/rewrite-testing-frameworks/pull/356 !

**Comment by knutwannheden** [comment]
@timtebeek Hmm. Doesn't #356 actually fix #208 instead of this issue?

**Comment by timtebeek** [comment]
No #356 is a new one that was added yesterday, and does actually fix this one as seen in the unit tests
https://github.com/openrewrite/rewrite-testing-frameworks/blob/6219e8198d0680f80b3b7afa32886d7778d95f94/src/test/java/org/openrewrite/java/testing/junit5/RemoveDuplicateTestTemplatesTest.java#L50-L67

**Comment by knutwannheden** [comment]
I see. Thanks. I remember seeing that #353 was linked to this one. But I now see that that one is still open.
