### ISSUE TITLE
Bring Gradle dependency upgrades to parity with maven dependency upgrades

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-testing-frameworks#316]
Anywhere we use a Maven recipe to bump a dependency we should have a corresponding gradle change.

**Comment by knutwannheden** [comment]
See also https://github.com/openrewrite/rewrite-spring/issues/288

**Comment by timtebeek** [comment]
Picked up in https://github.com/openrewrite/rewrite-testing-frameworks/commit/f25ff0b0ed2b9e227b07972986b35f7a1cc958af
