### ISSUE TITLE
Consider logic change of mockito argument matchers

### ISSUE THREAD

**Issue by klauerm** [openrewrite/rewrite-testing-frameworks#319]
From Mockito 1.x to 3.x the logic of the argument matchers has changed. Mockito.any(<Class>) doesn't match a null value that is passed to the mocked method as parameter. (see https://site.mockito.org/javadoc/current/org/mockito/ArgumentMatchers.html and https://javadoc.io/static/org.mockito/mockito-core/5.1.1/org/mockito/ArgumentMatchers.html#nullable(java.lang.Class))

Therefore, it is necessary to replace all instances of Mockito.anyString() and any(<Class>) with nullable(String) or nullable(<Class>). Nullable behaves exactly like anyString() or any(<Class>) in the previous Mockito version 1.x.

**Comment by timtebeek** [comment]
Good that you've pointed out these specifics; I've extracted the below table from the 5.1.1 documentation for clarity:

Modifier and Type | Method | Description
-- | -- | --
`static <T> T` | [any()](https://javadoc.io/static/org.mockito/mockito-core/5.1.1/org/mockito/ArgumentMatchers.html#any()) | Matches anything, including nulls and varargs.
`static <T> T` | [any](https://javadoc.io/static/org.mockito/mockito-core/5.1.1/org/mockito/ArgumentMatchers.html#any(java.lang.Class))​([Class](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html?is-external=true)<T> type) | Matches any object of given type, excluding nulls.
`static <T> T` | [nullable](https://javadoc.io/static/org.mockito/mockito-core/5.1.1/org/mockito/ArgumentMatchers.html#nullable(java.lang.Class))​([Class](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html?is-external=true)<T> clazz) | Argument that is either null or of the given type.

With this further note on [any](https://javadoc.io/static/org.mockito/mockito-core/5.1.1/org/mockito/ArgumentMatchers.html#any(java.lang.Class))​([Class](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html?is-external=true)<T> type):
> Since Mockito 2.1.0, only allow non-null instance of , thus null is not anymore a valid value. As reference are nullable, the suggested API to match null would be [isNull()](https://site.mockito.org/javadoc/current/org/mockito/ArgumentMatchers.html#isNull()). We felt this change would make tests harness much safer that it was with Mockito 1.x.

**Comment by timtebeek** [comment]
Are you proposing then that for the migration from 1.x to 3.x+ we swap `any(Class)` to `nullable(Class)` to adhere to the exact same semantics, rather than retain `any(Class)` with slightly changed `null` handling semantics?

As a developer I'd be _mildly_ surprised about such a change, or at least until I read up on the specifics like we see above. It's not been pointed out as a bug before; but perhaps like you said `nullable(Class)` is the correct one-to-one replacement to do no harm.

I imagine this would be a [yaml only change in Mockito1to3Migration](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/resources/META-INF/rewrite/mockito.yml#L32), which could make this relatively straightforward.

**Comment by klauerm** [comment]
We did a huge Mockito upgrade in our company with million lines of code. The main root cause for the afterwards failing tests was this semantic change. We weren't aware of it upfront and so the affected colleagues did search and replace in their IDEs which costs a lot of time. So having this fix would be beneficial for all upcoming Mockito upgrades.

**Comment by timtebeek** [comment]
Yes sorry to hear this particular aspect of that migration has not been as smooth as you would have hoped; I think just inserting
```yaml
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.mockito.ArgumentMatchers any(java.lang.Class)
      newMethodName: nullable
```
[into `Mockito1to3Migration`](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/resources/META-INF/rewrite/mockito.yml#L32) would be enough to resolve this issue, as well as any test fixes; would you agree?

You're also able to run this change separately with a temporary [`rewrite.yml` at the project root](https://docs.openrewrite.org/running-recipes/getting-started#step-5-run-a-recipe-with-yaml-configuration), which is even easier (and faster!) with our platform if you'd like to explore that.

**Comment by timtebeek** [comment]
No need to be sorry! We grateful for all your help, both in thorough contributions such as the PowerMock recipe, as well as detailed reports on imperfections such as this one. I've added the `anyString` case to the table above and added this to the backlog.

**Comment by timtebeek** [comment]
Picked up as a quick attempt in https://github.com/openrewrite/rewrite-testing-frameworks/pull/320; welcome to look that over, but no requirement whatsoever. :)
