### ISSUE TITLE
Simplify chained AssertJ assertions

### ISSUE THREAD

**Issue by TobiX** [openrewrite/rewrite-testing-frameworks#348]
## What problem are you trying to solve?

After running OpenRewrite to move assertions to AssertJ "best practices", SonarLint/SonarQube complains about many assertions not using the "best" form of AssertJ assertions (Rule: https://rules.sonarsource.com/java/RSPEC-5838). It would be nice if OpenRewrite could apply these suggestions automatically.

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?

Maybe, but currently not enough time.

**Comment by timtebeek** [comment]
Hi @TobiX ; thank you for reporting these issues here & the helpful kink to RSPEC-5838. Looking through the findings we appear to already cover some of those rewrites through [recent Assert recipe additions](https://github.com/openrewrite/rewrite-testing-frameworks/tree/main/src/main/java/org/openrewrite/java/testing/assertj):
1. [UseExplicitContains.java](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/assertj/UseExplicitContains.java)
2. [UseExplicitIsEmpty.java](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/assertj/UseExplicitIsEmpty.java)
3. [UseExplicitSize.java](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/assertj/UseExplicitSize.java)

But we can always to better with new recipes to handle the remaining cases. Our [upcoming support for refaster templates](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/lang/UseStringIsEmpty.java#L22-L30) should make it a whole lot easier to contribute such rewrite recipes, and we'll gladly coach anyone to such a contribution.

Are there any examples in RSPEC-5838 in particular that you would like to prioritize?

**Comment by TobiX** [comment]
Hmm, interesting. Some notes:
-  `org.openrewrite.java.testing.assertj.Assertj` doesn't contain `UseExplicitIsEmpty` yet? (This is probably why I missed some of those changes)
- Not sure if `org.openrewrite.java.testing.assertj.JUnitToAssertj` should contain `org.openrewrite.java.testing.assertj.Assertj`? The migration creates many "un-optimal" assertions, so maybe at least document that it's useful to run them at the same time?
- I think my main gripe was that there is no recipe to replace `.hasSize(0)` with `isEmpty()` or `isEqualTo(0)` with `isZero()` 😆

**Comment by timtebeek** [comment]
Welcome to add those two changes if you're looking to contribute; https://github.com/openrewrite/rewrite-testing-frameworks/blob/efcc1e4904e90d0c7a1cbd6b1a230ff698a3917d/src/main/resources/META-INF/rewrite/assertj.yml#L24-L29 Should be a small change indeed for some worthwhile improvements.
Thanks either way for pointing those out!

**Comment by timtebeek** [comment]
I've just added UseExplicitIsEmpty to AssertJ best practices in https://github.com/openrewrite/rewrite-testing-
frameworks/commit/8fb92424e26f11c4a68e3f769feee3d2ea4c0c6e
`JUnitToAssertj` is already part of `Assertj best practices`,
so I'm not adding `Assertj best practices` to `JUnitToAssertj`.
I suggest you run those the other way around. ;)

Apart from that open to accept more of the https://rules.sonarsource.com/java/RSPEC-5838 suggested replacements as separate recipes.

**Comment by timtebeek** [comment]
Array cases not yet handled; attempt was made in https://github.com/openrewrite/rewrite-testing-frameworks/pull/385/commits/bf977da42d3ca8850034fc7c8599d60a15c78eaa but reverted due to complexity of array.length not being a method invocation in the current recipe implementation. Linked here in case we want to cover that still.

**Comment by timtebeek** [comment]
Adding a reason such as in `assertThat(actual.isEmpty()).as("Reason").isTrue();` is also not yet supported.
