### ISSUE TITLE
Could not find artifact org.openrewrite.gradle.tooling:model:jar:0.8.4

### ISSUE THREAD

**Issue by rajaavaya** [openrewrite/rewrite-testing-frameworks#352]
Hi ,
I am getting error "Could not find artifact org.openrewrite.gradle.tooling:model:jar:0.8.4" when I ran this junit4 to junit test case migration command:
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.testing.junit5.JUnit5BestPractices

I don't see the jar in the repo and the latest jar is 0.9.0.

**Comment by timtebeek** [comment]
We've had some recent releases that I'm hopeful have resolved this issue
https://github.com/openrewrite/rewrite-maven-plugin/releases/tag/v5.2.4
https://github.com/openrewrite/rewrite-testing-frameworks/releases/tag/v2.0.4

Your command doesn't explicitly use any particular version, but if you rerun it, that should pick up the above new versions to hopefully resolve your issue. Let us know if that's not the case!
