### ISSUE TITLE
TemporaryFolderToTempDir should use Path instead of File

### ISSUE THREAD

**Issue by gadams00** [openrewrite/rewrite-testing-frameworks#37]
The junit TemporaryFolderToTempDir visitor currently replaces `@Rule TemporaryFolder tempDir = new TemporaryFolder();` with `@TempDir File tempDir;` and adds static methods to use in replacements for invocations of TemporaryFolder.newFile and newFolder. Instead of File, we should replace tempDir with a Path instance variable, skip the static method creation, and replace newFile with `Path.resolve({file-path}).toFile()` and newFolder with `Path.resolve({folder-path}).toFile().mkdirs()`

**Comment by sambsnyd** [comment]
You're right, that would be better, but this is very low priority. Closing for now.
