### ISSUE TITLE
@ParameterizedTest annotation is being added to non-test methods

### ISSUE THREAD

**Issue by talios** [openrewrite/rewrite-testing-frameworks#397]
## What version of OpenRewrite are you using?

I am using

- rewrite-maven-plugin 5.4.0
- rewrite-testing-frameworks 2.0.9

## How are you running OpenRewrite?

Using the Maven Plugin, with a tiles-maven-plugin based project (rewrite plugin config in a tile).

```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>5.4.0</version>
  <configuration>
    <activeRecipes>
      <recipe>org.openrewrite.staticanalysis.CodeCleanup</recipe>
      <recipe>org.openrewrite.staticanalysis.CommonStaticAnalysis</recipe>
      <recipe>org.openrewrite.staticanalysis.MissingOverrideAnnotation</recipe>
      <recipe>org.openrewrite.staticanalysis.AtomicPrimitiveEqualsUsesGet</recipe>
      <recipe>org.openrewrite.staticanalysis.AvoidBoxedBooleanExpressions</recipe>
      <recipe>org.openrewrite.staticanalysis.CaseInsensitiveComparisonsDoNotChangeCase</recipe>
      <recipe>org.openrewrite.staticanalysis.CatchClauseOnlyRethrows</recipe>
      <recipe>org.openrewrite.staticanalysis.NewStringBuilderBufferWithCharArgument</recipe>
      <recipe>org.openrewrite.staticanalysis.CombineSemanticallyEqualCatchBlocks</recipe>
      <recipe>org.openrewrite.staticanalysis.NoFinalizedLocalVariables</recipe>
      <recipe>org.openrewrite.staticanalysis.EqualsAvoidsNull</recipe>
      <recipe>org.openrewrite.java.RemoveUnusedImports</recipe>
      <!-- <recipe>org.openrewrite.java.UseStaticImport</recipe> -->
      <recipe>org.openrewrite.java.security.JavaSecurityBestPractices</recipe>
      <recipe>org.openrewrite.java.testing.junit5.JUnit5BestPractices</recipe>

      <recipe>org.openrewrite.java.logging.slf4j.ParameterizedLogging</recipe>
      <recipe>org.openrewrite.java.migrate.UpgradeToJava17</recipe>
    </activeRecipes>
    <activeStyles>
    </activeStyles>
  </configuration>
  <dependencies>
    <dependency>
      <groupId>org.openrewrite.recipe</groupId>
      <artifactId>rewrite-static-analysis</artifactId>
      <version>1.0.4</version>
    </dependency>
    <dependency>
      <groupId>org.openrewrite.recipe</groupId>
      <artifactId>rewrite-logging-frameworks</artifactId>
      <version>2.0.2</version>
    </dependency>
    <dependency>
      <groupId>org.openrewrite.recipe</groupId>
      <artifactId>rewrite-java-security</artifactId>
      <version>2.0.2</version>
    </dependency>
    <dependency>
      <groupId>org.openrewrite.recipe</groupId>
      <artifactId>rewrite-testing-frameworks</artifactId>
      <version>2.0.9</version>
    </dependency>
    <dependency>
      <groupId>org.openrewrite.recipe</groupId>
      <artifactId>rewrite-migrate-java</artifactId>
      <version>2.0.9</version>
    </dependency>
  </dependencies>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

Given the following method:

```
@MethodSource
static Stream<Integer> midnightIntervals() {
  return Stream.of(1, 2, 3);
}
```

I expect to see no changes, however, the `@ParameterizedTest` annotation gets applied to the source function, which then fails to run as it's not actually a test.

```
@ParameterizedTest
@MethodSource
static Stream<Integer> midnightIntervals() {
  return Stream.of(1, 2, 3);
}
```

**Comment by timtebeek** [comment]
Hi @talios ; Those changes are most likely made by a recent recipe addition in #353 to 
["Add missing @ParameterizedTest annotation when @ValueSource is used or replace @Test with @ParameterizedTest"](https://docs.openrewrite.org/recipes/java/testing/junit5/addparameterizedtestannotation)
That was recipe was added after a request in #208 and does seem to align with [how `@MethodSource` is used in the JUnit 5 user guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-MethodSource).

I'd not seen your use of applying `@MethodSource` to the generating method before; Up to now I'd only seen that used on the test method using a generated method. Could you tell us why you've added that annotation to the generating method here, and what that adds to your project?

My expectation would be that it's not necessary to annotate the generating `midnightIntervals` method with `@MethodSource` above, and then the recipe would not have added the `@ParameterizedTest` annotation. Could that be a workable alternative for you?

If not then a perhaps a minimal reproduction of how a test class looks on your end would help us understand better, and adjust accordingly.

**Comment by talios** [comment]
Looks like this was a bug on my part - looks like an early attempt at automating the move from TestNG to Junit5 added that annotation on the wrong method - it was on the test _and_ the source.

Without the new `@ParameterizedTest` annotation, it was simply ignored.

Happy to close this now.

**Comment by timtebeek** [comment]
Thanks for getting back to us on this!
