### ISSUE TITLE
`Simplify AssertJ chained assertions` should not use `hasSize()`, `hasSameSizeAs()` or `hasSameSizeAs(int)`

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-testing-frameworks#398]
As discovered through https://github.com/spring-projects/spring-security/pull/13619 & https://github.com/spring-cloud/spring-cloud-config/pull/2315

### Problem
1. The zero handling ends up replacing this unwanted pattern.
```diff
-assertThat(objectIdentities.size()).isEqualTo(0);
+assertThat(objectIdentities).hasSize();
```

2. The `.size()).isEqualTo(1)` is incorrectly changed into `hasSameSizeAs(1)`.
```diff
 		given(claimSetConverter.convert(any(Map.class))).willReturn(Collections.singletonMap("custom", "value"));
this.jwtDecoder.setClaimSetConverter(claimSetConverter);
Jwt jwt = this.jwtDecoder.decode(SIGNED_JWT);
-		assertThat(jwt.getClaims().size()).isEqualTo(1);
-		assertThat(jwt.getClaims().get("custom")).isEqualTo("value");
+		assertThat(jwt.getClaims()).hasSameSizeAs(1);
+		assertThat(jwt.getClaims()).containsEntry("custom", "value");
}
```
**From:** `oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java`

#### Recipes in example diff:
- `org.openrewrite.java.testing.assertj.SimplifyChainedAssertJAssertion`

### References:
- [View original result](https://app.moderne.io/results/bGVuS/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsIm9yaWdpbiI6ImdpdGh1Yi5jb20iLCJwYXRoIjoic3ByaW5nLXByb2plY3RzL3NwcmluZy1zZWN1cml0eSIsImJyYW5jaCI6Im1haW4ifQ==?referrer=%2Fresults%2FbGVuS)
- Recipe ID: `org.openrewrite.java.testing.assertj.SimplifyChainedAssertJAssertion`
- Recipe Name: `Simplify AssertJ chained assertions`
- Repository: `spring-projects/spring-security/main`
- Created at Sun Aug 06 2023 23:36:52 GMT+0200 (Central European Summer Time)

**Comment by timtebeek** [comment]
There's a few more failures if you look at the reverts I had to do in
- https://github.com/spring-projects/spring-security/pull/13619/commits
- https://github.com/spring-cloud/spring-cloud-config/pull/2315/commits

Was pretty neat seeing the recipes work at scale; with the above fixes it should work even better.

@AlekSimpson would you be able to look at these failures?

**Comment by timtebeek** [comment]
Another big issue was dropping the last method invocation in this change:
```diff
-assertThat("johndoe".equals(principalSid.getPrincipal())).isTrue();
+assertThat("johndoe").isEqualTo(principalSid);

-assertThat("ROLE_TEST".equals(gaSid.getGrantedAuthority())).isTrue();
+assertThat("ROLE_TEST").isEqualTo(gaSid);
```

**Comment by AlekSimpson** [comment]
Yes I can look these
