### ISSUE TITLE
TestsShouldIncludeAssertions does not respect Mockito verifyNoInteractions / verifyNoMoreInteractions

### ISSUE THREAD

**Issue by segfaultx** [openrewrite/rewrite-testing-frameworks#402]
Hi i have found out that the TestsShouldIncludeAssertions Recipe does not respect the following mockito methods:

- verifyNoInteractions
- verifyNoMoreInteractions

and keeps adding the "assertDoesNotThrow" wrapping Method to tests that only use these mockito verifications, which i think might not be intended.

## What version of OpenRewrite are you using?
Here is my openrewrite maven configuration:

```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>5.4.2</version>
  <configuration>
    <activeRecipes>
      <recipe>org.openrewrite.java.testing.cleanup.TestsShouldIncludeAssertions</recipe>
    </activeRecipes>
  </configuration>
  <dependencies>
    <dependency>
      <groupId>org.openrewrite.recipe</groupId>
      <artifactId>rewrite-testing-frameworks</artifactId>
      <version>2.0.9</version>
    </dependency>
  </dependencies>
</plugin>
```

## How are you running OpenRewrite?

I am running openrewrite through the cli via 
`./mvnw rewrite:run`

## Is your project public? If so, can you share a link to it?
Here is an example project i set up:
https://github.com/segfaultx/openrewriteexample.git

## What is the smallest, simplest way to reproduce the problem?
Simply run `./mvnw rewrite:run`

The following test gets refactored:

```java
    @Test
    void testContainingVerifyNoMoreInteractionsDirectly() {
        Mockito.verifyNoInteractions(exampleService);
    }
```

to:

```java
    @Test
    void testContainingVerifyNoMoreInteractionsDirectly() {
        assertDoesNotThrow(() -> {
            Mockito.verifyNoInteractions(exampleService);
        });
    }
```

## What did you expect to see?

AssertDoesNotThrow should not be added to the test since there are mockito verifications

## What is the full stack trace of any errors you encountered?
No errors occuring

**Comment by knutwannheden** [comment]
Thanks for reaching out! As a workaround you can set the `additionalAsserts` option to `org.mockito.Mockito`.

Currently the recipe only checks for `org.mockito.Mockito#verify()`. But I agree that it should also check for `verifyNoInteractions()` and `verifyNoMoreInteractions()`.

**Comment by segfaultx** [comment]
thanks for providing such a quick fix!

**Comment by knutwannheden** [comment]
There should be a [snapshot build](https://docs.openrewrite.org/reference/snapshot-instructions) available soon. Otherwise you can use the workaround I proposed. Thanks for reporting again!
