### ISSUE TITLE
add useJUnitPlatform() to the test block in build.gradle file as part of junit4 to 5 conversion reipe

### ISSUE THREAD

**Issue by ajay-aggarwal** [openrewrite/rewrite-testing-frameworks#407]
## What problem are you trying to solve?
I ran recipe UpgradeSpringBoot_3_0 for migrating from springboot 2.x to springboot 3. We use gradle for build-tools. As part of this our junit4 test classes were converted to junit5. However now the converted test classes are not being recognized as test classes. One thing I noticed is that its not adding useJUnitPlatform() to the test block in build.gradle. Per my understanding this is needed to run junit5 tests.

## Describe the solution you'd like
add useJUnitPlatform() to the test block in build.gradle file

**Comment by shanman190** [comment]
This is now fixed via https://github.com/openrewrite/rewrite-testing-frameworks/commit/402a8cb47f02053bcd7fb7c1d5db1dbc43a63955.
