### ISSUE TITLE
Remove @RunWith(JUnitPlatfrom.class) when migrating to JUnit 5

### ISSUE THREAD

**Issue by Viskocrack** [openrewrite/rewrite-testing-frameworks#408]
## What problem are you trying to solve?

When using the org.openrewrite.java.testing.junit5.JUnit4to5Migration, if there are tests using the annotation @RunWith(JUnitPlatform.class), the annotation and content of it remains. Causing a compilation error after migration.

## Describe the solution you'd like

Remove the annotation and its contents when using the recipe.

## Have you considered any alternatives or workarounds?

The only way to i've found to fix this is manually adding the junit-vintage-engine OR manually removing the annotation from all tests.

Currently running OR version 5.4.2 with maven

**Comment by timtebeek** [comment]
You'll want to run this recipe instead (from [the rewrite-spring module](https://github.com/openrewrite/rewrite-spring)) to get the results you're after:
https://docs.openrewrite.org/recipes/java/spring/boot2/springboot2junit4to5migration

We've grouped any Spring specific migrations in that module, such that modules for Quarkus and Micronaut can use rewrite-testing-frameworks too.

Hope that helps!
