### ISSUE TITLE
Mockito > 5.2.0 remove mockito-inline

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-testing-frameworks#410]
## What problem are you trying to solve?

Starting with Mockito 5.3.0, the `mockito-inline` dependency is no longer published :  

> The inline mockmaker is the default mockmaker since 5.0.0 and we stopped publishing the artifact in 5.3.0. You can replace it with mockito-core to get the same outcome.

## What precondition(s) should be checked before applying this recipe?

- mockito-inline is a dependency

## Describe the situation before applying the recipe

```xml
       <mockito.version>5.2.0</mockito.version>
```

```xml

<dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <scope>test</scope>
        </dependency>

```

## Describe the situation after applying the recipe

Mockito needs to be upgraded to > 5.2.0

```xml
       <mockito.version>5.5.0</mockito.version>
```

1. If mockito-core is not part of the dependencies, then mockito-inline can be replaced with mockito-core

```diff

@@ -80,7 +80,7 @@
         </dependency>
         <dependency>
             <groupId>org.mockito</groupId>
-            <artifactId>mockito-inline</artifactId>
+            <artifactId>mockito-core</artifactId>
             <scope>test</scope>
         </dependency>
         <dependency>

```

2. If Mockito-core is part of the dependency, then inline can be removed

```diff


-        <dependency>
-            <groupId>org.mockito</groupId>
-            <artifactId>mockito-inline</artifactId>
-            <scope>test</scope>
-        </dependency>

```

## Additional context 

https://github.com/mockito/mockito/issues/3039
https://github.com/mockito/mockito/issues/2877

**Comment by timtebeek** [comment]
Thanks for the detailed report @yeikel ! I've added it to the list in 
- #295 

We can keep this one open, as it's easier to pick off individual items, or move your comment there, whichever you prefer.

**Comment by IsaacHu** [comment]
Previously, we can use mockito-inline to mock the final class. 
As **[Mockito 5] switches the default mockmaker to mockito-inline**, we removed the mockito-inline dependency, and then the mock of the final class failed. 
Is there any solution for that? 
coz mockito-inline no longer upgrades after 5.2.0, thx.
