### ISSUE TITLE
Post migration 4 to 5, gradle.kts file depencideis are not changed from 4.x to 5.x

### ISSUE THREAD

**Issue by nagkumar** [openrewrite/rewrite-testing-frameworks#413]
Post-migration 4 to 5, build.gradle.kts file dependencies are not changed from 4.x to 5.x

**Comment by knutwannheden** [comment]
Hi @nagkumar! Thanks for your report. We don't support Gradle Kotlin scrips just yet (only Groovy), but are getting close. We're tracking progress on that in this issue
- https://github.com/openrewrite/rewrite/issues/3291

You can subscribe to the above issue to be notified when support is finished, or watch out for upcoming OpenRewrite releases and their release notes.

Hope that helps! And I hope you don't mind me closing this issue in favor of the earlier issue. Your reminder is appreciated!
