### ISSUE TITLE
org.openrewrite.java.testing.hamcrest.MigrateHamcrestToAssertJ

### ISSUE THREAD

**Issue by nagkumar** [openrewrite/rewrite-testing-frameworks#414]
post migration harmcrest jars are removed and assertj jars are not added to build.gradle.kts script

**Comment by timtebeek** [comment]
Correct; we don't yet fully support adding dependencies to Gradle kotlin files; you can follow along to support here:
- https://github.com/openrewrite/rewrite/issues/3291
