### ISSUE TITLE
Opt-out from junit4->junit5 conversion for classes that can't be migrated to junit5 yet

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite-testing-frameworks#422]
## What problem are you trying to solve?

I am trying to apply `org.openrewrite.java.testing.junit5.JUnit4to5Migration`, however, it breaks certain classes which can't easily transformed to junit5.

## Describe the solution you'd like

I would like to have an annotation so I can specify classes that should be left intact concerning `@Test` annotations.

pgjdbc has `BaseTest4` class, and several other JUnit4 tests inherit the class, and override methods, including `@Before`: https://github.com/pgjdbc/pgjdbc/blob/9cf9f36a1d3a1edd9286721f9c0b9cfa9e8422e3/pgjdbc/src/test/java/org/postgresql/test/jdbc2/BaseTest4.java#L86-L98

Of course, migrating `BaseTest4` to JUnit5 breaks all the classes that extend `BaseTest4`, so I would like to have an annotation so OpenRewrite could skip replacing `@Test` and `public -> package private` changes.

## Have you considered any alternatives or workarounds?

A workaround is probably to completely exclude the problematic tests from OpenRewrite processing.
It would be nice if OpenRewrite could automatically opt-out `@Test` conversions for classes extending the ones that are excluded from `@Test` processing.

## Additional context

https://github.com/pgjdbc/pgjdbc/pull/2979

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

No idea yet.

**Comment by vlsi** [comment]
For now, I have manually excluded the files from OpenRewrite processing, so the issue is not pressing.

However, I've got an implementation idea: what do you think of supporting `@SuppressWarnings("org.openrewrite.java.testing.junit5.MigrateAssumptions")` so the users could suppress execution of the said rule within the method, class or variable declaration statement.

**Comment by SimonVerhoeven** [comment]
Would using a precondition be a viable option? https://docs.openrewrite.org/reference/yaml-format-reference#preconditions

**Comment by vlsi** [comment]
It might indeed help to exclude files by matching “extends BaseTest4” however, there are cases where BaseTest4 is indirect superclass.
It would be great to execute some of the recipes like code cleanup even for junit4 tests. As far as I understand, precondition completely skips class from processing

**Comment by timtebeek** [comment]
Preconditions, when used from Yaml, can be applied to restrict execution of the `recipeList` of the same recipe. You could create a `rewrite.yml` and use that to limit execution to particular files, and run specific recipe lists for those. Not quite sure I'd recommend that, but it's what we currently offer.

We don't yet support any way to suppress recipe execution on particular files, but you could create your own annotation, and use that in a precondition as well.

Given the above I find it hard to arrive at a clear other way we can automate these exclusions, especially as that relates to rewrite-testing-frameworks. Would you agree with closing this issue as not something that's actionable in the current form?

**Comment by timtebeek** [comment]
Closing this one as not really actionable from our end: our JUnit 5 migration assumes it to be a complete migration, adding and removing dependencies. That's not a great fit to having some classes remain on JUnit 4. With preconditions and excludes you can maybe achieve some of this, as indicated.
