### ISSUE TITLE
AssertToAssertions puts a comma on a new line

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite-testing-frameworks#423]
## What version of OpenRewrite are you using?

org.openrewrite.rewrite.gradle.plugin:6.4.3

## How are you running OpenRewrite?

`./gradlew rewriteRun`, see https://github.com/pgjdbc/pgjdbc/pull/2979/

## What is the smallest, simplest way to reproduce the problem?

Before (see https://github.com/pgjdbc/pgjdbc/blob/9cf9f36a1d3a1edd9286721f9c0b9cfa9e8422e3/pgjdbc/src/test/java/org/postgresql/util/LazyCleanerTest.java#L129-L133 ):

```java
    assertThrows(
        "Exception from cleanable.clean() should be rethrown",
        IllegalStateException.class,
        cleanable::clean
    );
```

## What did you expect to see?

```java
    assertThrows(
        IllegalStateException.class,
        cleanable::clean,
        "Exception from cleanable.clean() should be rethrown"
    );
```

## What did you see instead?

```java
    assertThrows(
        IllegalStateException.class,
        cleanable::clean
    ,
        "Exception from cleanable.clean() should be rethrown");
```

**Comment by knutwannheden** [comment]
@vlsi Thanks for reporting. The fix has been deployed to https://app.moderne.io/.
