### ISSUE TITLE
Make visibility modifier change by UpdateTestAnnotation optional

### ISSUE THREAD

**Issue by magicwerk** [openrewrite/rewrite-testing-frameworks#441]
The recipe UpdateTestAnnotation doing the migration of the @Test annotation from JUnit 4 to 5 also removes the public modifier from the test method.
This seems arbitrary to me as this may not be desired.
It is true that JUnit 5 does not require test lifecycle methods to be public, but this is not a requirement.

With the current implementation, these changes must be reverted manually if the test methods should remain public
(or by writing an additional rule which does the opposite of TestsShouldNotBePublic).

I would propose to make the removal of the visibility modifier configurable by adding a respective @Option to the recipe.

## What version of OpenRewrite are you using?
rewrite-testing-frameworks-2.1.4

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
I could try to provide a PR for this.

**Comment by timtebeek** [comment]
It seems indeed like that change might be best not done by UpdateTestAnnotation, even though the tests currently verify that.
https://github.com/openrewrite/rewrite-testing-frameworks/blob/e383281491aa96ed00a689233e4af41b2f80b34b/src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java#L38-L72

Instead it would be best if we only make that change when running `TestsShouldNotBePublic` https://github.com/openrewrite/rewrite-testing-frameworks/blob/e383281491aa96ed00a689233e4af41b2f80b34b/src/main/resources/META-INF/rewrite/junit5.yml#L29

That way folks indeed have a choice of not removing the public modifier while still converting their test methods. I'd welcome a PR and review that shortly if you're able to provide one.
