### ISSUE TITLE
junit4->5 rewrites @Test(1000 /*ms*/) to @Timeout(1000 /*sec*/) which breaks test logic

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite-testing-frameworks#450]
## What version of OpenRewrite are you using?

`latest.integration`

JUnit4 uses milliseconds for the timeout (there's no way to configure the unit), and JUnit5 uses `TimeUnit.SECONDS` by default.

I believe this is a wrong test: https://github.com/openrewrite/rewrite-testing-frameworks/blob/326c048c86f31e135a853e0f5d4e4bccb0769644/src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java#L275-L302

I think OpenRewrite should convert `@Test(timeout = 5000)` to `@Timeout(5)`; and it should convert `@Test(timeout = 500)` to `@Timeout(value = 500, unit = TimeUnit.MILLISECONDS)`.

**Comment by timtebeek** [comment]
That's indeed a bug, and a nasty one at that as well. Thanks for pointing it out!

**Comment by vlsi** [comment]
It might make sense to add a rewrite rule that would detect "too large timeouts" and suggest converting them to seconds.
For instance: imagine someone has `@Timeout(1000)`. I am 100% sure they meant `1 second` rather than `1000 seconds = 16.7 minutes`.

As a workaround, users could type `@Timeout(value = 17, unit = TimeUnit.MINUTES)` or `@Timeout(value = 1000, unit = TimeUnit.SECONDS)`.

So the rewrite rule could be `@Timeout(6000)` => `@Timeout(60)`.

**Comment by timtebeek** [comment]
Yes I indeed think a separate recipe is in order that detects and corrects such implausible values; See also  https://github.com/openrewrite/rewrite-testing-frameworks/pull/451#issue-2065850321

**Comment by timtebeek** [comment]
Should be fixed for the time being; would you want to log a separate issue for detecting implausible timeouts and simplifying existing timeouts?

**Comment by vlsi** [comment]
I've filed https://github.com/openrewrite/rewrite-testing-frameworks/issues/452
