### ISSUE TITLE
Problem with using JUnit4to5Migration

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-testing-frameworks#457]
### Discussed in https://github.com/openrewrite/rewrite/discussions/3911

<div type='discussions-op-text'>

<sup>Originally posted by **ErhardSiegl** January 13, 2024</sup>
I'm rather new to OpenRewrite. I tried to migrate a project from Junit4 to Junit5 with `org.openrewrite.java.testing.junit5.JUnit4to5Migration`. The Java files worked fine, but the the Jupiter dependencies were not added to the pom.xml. When I changed the recipe in the following way it worked:
```
3c3
< name: org.openrewrite.java.testing.junit5.JUnit4to5Migration
---
> name: org.openrewrite.java.testing.junit5.JUnit4to5Migration1
68c68
<       onlyIfUsing: org.junit.jupiter.api.Test
---
>       onlyIfUsing: org.junit.Test
70a71,79
>       groupId: org.mockito
>       artifactId: mockito-junit-jupiter
>       version: 5.x
>       onlyIfUsing: org.mockito.runners.MockitoJUnitRunner
>       acceptTransitive: true
>   - org.openrewrite.java.dependencies.RemoveDependency:
>       groupId: org.mockito
>       artifactId: mockito-all
>   - org.openrewrite.java.dependencies.AddDependency:
```
It seems that the `onlyIfUsing` needs the original class (`org.junit.Test`) and not the classname which is created by the recipe (`org.junit.jupiter.api.Test`). Is this a bug in the recipe or did I miss anything? I use the following configuration:

```
            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>5.17.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-migrate-java</artifactId>
                        <version>2.5.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-testing-frameworks</artifactId>
                        <version>2.1.5</version>
                    </dependency>
                </dependencies>
            </plugin>
```
and start it with `mvn rewrite:run -Drewrite.activeRecipes=org.openrewrite.java.testing.junit5.JUnit4to5Migration1`
[rewrite.yml.txt](https://github.com/openrewrite/rewrite/files/13929460/rewrite.yml.txt)
</div>

**Comment by timtebeek** [comment]
Hi @erhardSiegl ; From the above it seems we might want to change the UseMockitoExtension recipe as defined here
https://github.com/openrewrite/rewrite-testing-frameworks/blob/430f635eb533e4a0070c4f17cc61d41574d692a3/src/main/resources/META-INF/rewrite/junit5.yml#L180-L197

Or maybe even better: add the above to [mockito.yml](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/resources/META-INF/rewrite/mockito.yml) such that it's included as part of `UseMockitoExtension`. Would you want to get credit for that change by opening a pull request here?

**Comment by ErhardSiegl** [comment]
Hi @timtebeek,
I'd rather not do the pull request since I'm unsure about the consequences and how to test the changes apart from my code.
I still don't understand the `onlyIfUsing: org.junit.jupiter.api.Test`. According to the examples in mockito.yml and junit5.yml this seems to be correct. However I had to change it to `onlyIfUsing: org.junit.Test` to make it work.
The 
```
>   - org.openrewrite.java.dependencies.RemoveDependency:
>       groupId: org.mockito
>       artifactId: mockito-all
```
is apparently not included in the recipes. But maybe `mockito-all` was not the best choice in the first place. My code is a couple of years old.

**Comment by timtebeek** [comment]
Hi @ErhardSiegl ; not problem at all; I've applied part of your suggested changes in https://github.com/openrewrite/rewrite-testing-frameworks/commit/216983b304a1eee1c1b8e857b663658af8fcb111 just now.

The `onlyIfUsing` looks at the lossless semantic tree type elements to see if the argument class is used in the current tree before adding a dependency. That conditionality allows recipes to always run, but only make changes when those types are used. It is sensitive to recipe ordering, and I suspect you had trouble coming from Mockito 1.x here, as evidenced by the use of `mockito-all`.

To answer your question about how recipe changes are tested, you can have a look at this example test that's part of the Mockito and JUnit Jupiter migration.
https://github.com/openrewrite/rewrite-testing-frameworks/blob/53cfd4cdd4fbcf472b3cb7f0e00d217cea31d6a4/src/test/java/org/openrewrite/java/testing/junit5/RunnerToExtensionTest.java#L29-L68

Similar tests can be added if you feel there are cases left uncovered. Thanks for reporting your issue and suggested improvements!
