### ISSUE TITLE
Validate rewrite-testing-frameworks against various public repositories

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#46]
Test the JUnit 4 to 5 migration by applying it to a set of OSS projects

**Comment by okundzich** [comment]
Please also add a list of repos that pass validation

**Comment by pway99** [comment]
**spring-cloud-sleuth**
- [X] Autoformat error in SleuthReactorProperties - duplicated value and lost space
- [ ] Validation Complete
**spring-cloud-netflix-core**
- [X] TabsAndIndentsVisitor - method declaration and tab indentation bug
- [ ] Imports - star imports bug
- [ ] Validation Complete

**Comment by pway99** [comment]
Closing this issue in favor of working discovered issues individually
