### ISSUE TITLE
RemoveTestPrefix should have `testing` untouched

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-testing-frameworks#471]
```diff
-    void testingEnvironment() {
+    void ingEnvironment() {
```

The prefix `testing` should be kept unmodified (or completly removed?)

**Comment by timtebeek** [comment]
Ouch, yeah I agree with you there! We should probably check that the 5th character is at least uppercase or an underscore right here
https://github.com/openrewrite/rewrite-testing-frameworks/blob/6b5fd4f84e72fbd53da067522fb9d7a934c96315/src/main/java/org/openrewrite/java/testing/cleanup/RemoveTestPrefix.java#L91
