### ISSUE TITLE
RemoteTestPrefix: Smart new method name for capital letters

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-testing-frameworks#473]
```diff
-    void testRTFCharacters() {
+    void rTFCharacters() {
```

Wish:

```diff
-    void testRTFCharacters() {
+    void rtfCharacters() {
```

Meaning: Lowercase all but the last following subsequent capital letters.

**Comment by timtebeek** [comment]
Thanks! Indeed better. Went ahead and reused a convention that we have in `NameCaseConvention.format` to fix this, so if you find any similar cases those should be easy to fix.
