### ISSUE TITLE
JUnitAssertEqualsToAssertThat does not add import when custom classes are the arguments

### ISSUE THREAD

**Issue by timo-abele** [openrewrite/rewrite-testing-frameworks#479]
## What version of OpenRewrite are you using?

I am using

- Maven plugin v5.22.0
- rewrite-testing-frameworks v2.3.2

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
      <plugin>
        <groupId>org.openrewrite.maven</groupId>
        <artifactId>rewrite-maven-plugin</artifactId>
        <version>5.22.0</version>
        <configuration>
          <activeRecipes>
            <recipe>org.openrewrite.java.testing.assertj.JUnitAssertEqualsToAssertThat</recipe>
          </activeRecipes>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-testing-frameworks</artifactId>
            <version>2.3.2</version>
          </dependency>
        </dependencies>
      </plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
package org.example;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class ATest {

  @Test void testEquals() {
    Assertions.assertEquals(new OwnClass(), new OwnClass());
  }

  public record OwnClass(String a) {

    public OwnClass() {this("1");}
  }
}
```
It looks like the parameters have to be classes that the user has defined themselves.
(The issue can be reproduced with classes from the standard library if the second parameter (`actual`) is `null`, however then there is also a method call ambiguity after the user has manually added the missing import, and `null` has to be cast to something. But that is a separate issue)

## What did you expect to see?

```java
package org.example;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

class ATest {

  @Test void testEquals() {
    assertThat(new OwnClass()).isEqualTo(new OwnClass());
  }

  public record OwnClass(String a) {

    public OwnClass() {this("1");}
  }
}
```

## What did you see instead?

```java
package org.example;

import org.junit.jupiter.api.Test;

class ATest {

  @Test void testEquals() {
    assertThat(new OwnClass()).isEqualTo(new OwnClass());
  }

  public record OwnClass(String a) {

    public OwnClass() {this("1");}
  }
}
```

## What is the full stack trace of any errors you encountered?

```
stacktrace output here
```

**Comment by timtebeek** [comment]
Thanks for the report! intuitively I'd say this is possibly down to missing types on the methods generated from JavaTemplates we use.
https://github.com/openrewrite/rewrite-testing-frameworks/blob/70caf9d162158507fd29c8f4885af08fa174faa9/src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThat.java#L79-L83

When the correct types are present that prompts the `maybe` in `maybeAddImport` to actually add the imports. If the types are absent then the import is not added by default, as we're then unsure if it's actually being used. But since we're guaranteed to generate those methods here we might as well drop the `maybe` and always add the import.

**Comment by timtebeek** [comment]
I see you've already pushed up a draft pull request; thanks for that! Does the above help you enough to try your hand at a fix as well?

**Comment by timo-abele** [comment]
I think I got it, could you please review?
