### ISSUE TITLE
Assertj recipe creates semantic differences when converting Assert.fail().

### ISSUE THREAD

**Issue by motlin** [openrewrite/rewrite-testing-frameworks#504]
## What version of OpenRewrite are you using?

```xml
<groupId>org.openrewrite.maven</groupId>
<artifactId>rewrite-maven-plugin</artifactId>
<version>5.28.0</version>
```

```xml
<dependency>
    <groupId>org.openrewrite.recipe</groupId>
    <artifactId>rewrite-testing-frameworks</artifactId>
    <version>2.6.0</version>
</dependency>
```

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a multi module project.

## What is the smallest, simplest way to reproduce the problem?

Run `org.openrewrite.java.testing.assertj.Assertj` on code like this, where `Assert.fail()` takes a string argument.

```java
import org.junit.Assert;
import org.junit.jupiter.api.Test;

public class OpenrewriteTest
{
    @Test
    public void smokeTest()
    {
        String failMessage = "OpenrewriteTest.smokeTest() is not implemented yet";
        Assert.fail(failMessage);
    }
}
```

## What did you expect to see?

```java
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.fail;

public class OpenrewriteTest
{
    @Test
    public void smokeTest()
    {
        String failMessage = "OpenrewriteTest.smokeTest() is not implemented yet";
        fail(failMessage);
    }
}
```

## What did you see instead?

Code similar to the above, but there's an extra argument for the format string. When this runs, the fail exception is missing a message.

```java
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.fail;

public class OpenrewriteTest
{
    @Test
    public void smokeTest()
    {
        String failMessage = "OpenrewriteTest.smokeTest() is not implemented yet";
        fail("", failMessage);
    }
}
```

**Comment by timtebeek** [comment]
Thanks for the clear report. That's a bug indeed. Did you already explore what might cause the issue?

**Comment by timtebeek** [comment]
Should be fixed now in
- https://github.com/openrewrite/rewrite-testing-frameworks/commit/90540b8219cd1bef86f555839dd8b6915e7ccbd9

Thanks again! Let us know if you stumble across any other potential improvements.
