### ISSUE TITLE
Recipe org.openrewrite.java.dependencies.AddDependency not working... solo or in org.openrewrite.java.testing.junit5.JUnit4to5Migration

### ISSUE THREAD

**Issue by taijidude** [openrewrite/rewrite-testing-frameworks#506]
Hello, 

i'm trying to run the following recipe: https://docs.openrewrite.org/recipes/java/testing/junit5/junit4to5migration

but  it doesn't adds the junit 5 dependencies. And i'm struggling to figure out why not. 

Even my small test is not working: 

My pom.xml looks like this: 
```xml

... more maven stuff ...

       <dependency>
	   <groupId>junit</groupId>
	   <artifactId>junit</artifactId>
	   <version>4.13.2</version>
	   <scope>test</scope>
        </dependency>
</dependencies>	
	
<build>
	<plugins>
		<plugin>
			<groupId>org.openrewrite.maven</groupId>
			<artifactId>rewrite-maven-plugin</artifactId>
			<version>5.28.0</version>
			<dependencies>
				<dependency>
					<groupId>org.openrewrite.recipe</groupId>
					<artifactId>rewrite-migrate-java</artifactId>
					<version>2.11.0</version>
				</dependency>
				<dependency>
					<groupId>org.openrewrite.recipe</groupId>
						<artifactId>rewrite-testing-frameworks</artifactId>
						<version>2.6.0</version>
				</dependency>
			</dependencies>
		</plugin>
	</plugins>
	 </build>
```

My rewrite.yml looks like this: 

```yml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.testing.junit5.JUnit4to5Migration1
tags:
  - junit
  - testing
recipeList:
  - org.openrewrite.java.dependencies.AddDependency:
      groupId: org.junit.jupiter
      artifactId: junit-jupiter-params
      version: 5.x
      acceptTransitive: true
```

And my shell command looks like this: 

```shell
mvn rewrite:run -Drewrite.activeRecipes="org.openrewrite.java.testing.junit5.JUnit4to5Migration1" -Drewrite.configLocation="/c/Dev/test/rewrite.yml"
```

After this i would expect the new dependency in the pom. But nothing shows up. The output from the maven plugin shows nothing as well. 

```shell
[INFO] Scanning for projects...
[INFO]
[INFO] -------------< orw:test >--------------
[INFO] Building test - Impl 11.9-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ ejb ]---------------------------------
[INFO]
[INFO] >>> rewrite:5.28.0:run (default-cli) > process-test-classes @ test >>>
[INFO]
[INFO] --- java-formatter:1.0.0:install-git-hook (install-git-hook) @ test ---
[INFO]
[INFO] --- resources:3.3.0:resources (default-resources) @ test ---
[INFO] Copying 20 resources
[INFO]
[INFO] --- compiler:3.10.1:compile (default-compile) @ test ---
[WARNING]  Parameter 'compilerArguments' is deprecated: use {@link #compilerArgs} instead.
[WARNING]  Parameter 'optimize' (user property 'maven.compiler.optimize') is deprecated: This property is a no-op in {@code javac}.
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- build-helper:3.3.0:add-test-source (add-test-source) @ test ---
[INFO] Test Source directory: C:\Dev\gitrepo\test\src\integration-test\java added.
[INFO]
[INFO] --- resources:3.3.0:testResources (default-testResources) @ test ---
[INFO] Copying 0 resource
[INFO] Copying 1 resource
[INFO]
[INFO] --- compiler:3.10.1:testCompile (default-testCompile) @ test ---
[WARNING]  Parameter 'compilerArguments' is deprecated: use {@link #compilerArgs} instead.
[WARNING]  Parameter 'optimize' (user property 'maven.compiler.optimize') is deprecated: This property is a no-op in {@code javac}.
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< rewrite:5.28.0:run (default-cli) < process-test-classes @ test <<<
[INFO]
[INFO]
[INFO] --- rewrite:5.28.0:run (default-cli) @ test ---
[INFO] Using active recipe(s) [org.openrewrite.java.testing.junit5.JUnit4to5Migration1]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[INFO] Project [Billing Services - Impl] Resolving Poms...
[INFO] Project [Billing Services - Impl] Parsing source files
[INFO] Running recipe(s)...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.773 s
[INFO] Finished at: 2024-04-15T17:18:34+02:00
[INFO] ------------------------------------------------------------------------
```

What am i doing wrong? Or are my assumptions wrong?

**Comment by timtebeek** [comment]
Why are you running it like that? You should not have to define any `AddDependency` recipe or `rewrite.yml` file yourself.

Does your project get updated correctly when you
1. remove the plugin from your `pom.xml`
2. remove `rewrite.yml`
3. run the following command
      ```
      mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.testing.junit5.JUnit4to5Migration
      ```
      ?

**Comment by taijidude** [comment]
Thanks for the reply. Tried your command and it doesn't work for. The pom doesn't change. No Junit Jupiter Dependency added.

**Comment by timtebeek** [comment]
And to be sure: you don't already have a transitive dependency on JUnit Jupiter? Does your project not compile after the code changes are made?

It's been a couple weeks since we last released; I think there were some small fixes around adding dependencies that still need to go out in a new release. You could try our snapshot versions to see if that might help; otherwise it'll be a couple days until the next release.

**Comment by taijidude** [comment]
- I checked the transitiv dependencies with mvn dependency:tree. Just found the junit4 dependencies. 
- Yes, when i run your command from above i get compile errors. For junit annoations. 

Thanks for your help and the hint about the snapshot version. Will try this.

**Comment by taijidude** [comment]
Update: I generated a maven project with maven java quickstart archetype and then run the mvn command from above to migrate from junit4 to junit5. 

Works fine. So, there is some problem with the project i'm trying to migrate.

**Comment by timtebeek** [comment]
I only just now noticed you're using `build-helper-maven-plugin` to add a test source dependency at C:\Dev\gitrepo\test\src\integration-test\java. This is something we don't yet support, as [the Maven plugin on parses src/main and src/test](https://github.com/openrewrite/rewrite-maven-plugin/blob/56cc48b0c0faefb37812578a3d247c40599c99e8/src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java#L182-L183). Perhaps that factors in here? Do you also have a regular `src/test` folder as well?

**Comment by taijidude** [comment]
Thanks, will check it out in monday. Was on the backburner for a while.

**Comment by timtebeek** [comment]
Let's continue to track this issue:
- https://github.com/openrewrite/rewrite-maven-plugin/issues/755
