### ISSUE TITLE
HamcrestMatcherToAssertJ does not support matchers from "org.hamcrest.core.*"

### ISSUE THREAD

**Issue by Saturas89** [openrewrite/rewrite-testing-frameworks#519]
## What version of OpenRewrite are you using?
I am using

- Maven plugin v5.32.1
- rewrite-testing-frameworks v2.10.1

## How are you running OpenRewrite?
I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>5.32.1</version>
  <configuration>
    <activeRecipes>                                                    <recipe>org.openrewrite.java.testing.hamcrest.HamcrestMatcherToAssertJ</recipe>
    </activeRecipes>
  </configuration>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?
Using the hamcrest matchers from the core package.

```java
import static org.hamcrest.core.IsEqual.equalTo;
import static org.hamcrest.core.IsNot.not;
import static org.hamcrest.core.IsSame.sameInstance;
```

## What did you expect to see?
That the matchers are replaced with the assertJ assertions.

**Comment by timtebeek** [comment]
Thanks for bringing this to our attention @Saturas89 ! Should be fixed with
- https://github.com/openrewrite/rewrite-testing-frameworks/pull/523
