### ISSUE TITLE
Fix javadoc warnings

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-testing-frameworks#52]
In order to not need these lines: https://github.com/openrewrite/rewrite-testing-frameworks/blob/1d22bf0625ee06b5f390a525e1f104efcbbe501b/build.gradle.kts#L174-L179

Can circle back, just not able to fix this at the exact moment

**Comment by sambsnyd** [comment]
We're not publishing javadocs anywhere so I don't really care if they parse or not. The warnings are more annoying than the thing being warned about. Thanks for disabling them.
