### ISSUE TITLE
isGreaterThanOrEqualTo for java.util.Date by HamcrestMatcherToAssertJ should result isAfterOrEqualTo 

### ISSUE THREAD

**Issue by ssheikin** [openrewrite/rewrite-testing-frameworks#526]
## What version of OpenRewrite are you using?

I am using

- Maven/Gradle plugin 5.32.0
- rewrite-testing-frameworks 2.10.1

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a multi module project.
```xml
            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>5.32.0</version>
                <configuration>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.testing.hamcrest.MigrateHamcrestToAssertJ</recipe>
                    </activeRecipes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-testing-frameworks</artifactId>
                        <version>2.10.1</version>
                    </dependency>
                </dependencies>
            </plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
java.sql.Timestamp actualDate;
assertThat(actualDate, greaterThanOrEqualTo(expectedDate));
```

## What did you expect to see?

```java
assertThat(actualDate).isAfterOrEqualTo(expectedDate);
```

## What did you see instead?

```java
assertThat(actualDate).isGreaterThanOrEqualTo(expectedDate);
```

## What is the full stack trace of any errors you encountered?

```
[ERROR] cannot find symbol
[ERROR]   symbol:   method isGreaterThanOrEqualTo(java.sql.Timestamp)
[ERROR]   location: class org.assertj.core.api.AbstractDateAssert<capture#1 of ?>
```

**Comment by timtebeek** [comment]
Thanks for the report! Looks like we should be able to fix this quite easily by adding an additional step with an `argumentType: java.util.Date` that converts to `isAfterOrEqualTo` instead, and runs before the generalized case
https://github.com/openrewrite/rewrite-testing-frameworks/blob/65711d5ea8c296929e6f409c1650f64253558365/src/main/resources/META-INF/rewrite/hamcrest.yml#L70-L72

Just a couple lines of Yaml for a contribution if you're up for it; test optional as we're just reusing existing components. Is that something you'd like to contribute?

**Comment by ssheikin** [comment]
Sure! I'll try to take a look on my free evening.

**Comment by timtebeek** [comment]
Awesome, thanks a lot!
