### ISSUE TITLE
Is there a way to simulate a real Project in the rewrite-testing framework?

### ISSUE THREAD

**Issue by SilasSchaprian** [openrewrite/rewrite-testing-frameworks#535]
Hey sorry for opening a bug but i was not able to find a better place to ask my question.

I am authoring a recipe which does some "pre-refactoring checks" because i have to check a yaml key. 
Depending on the yaml key i am starting a recipe meant for another (xml)-file than the yaml SourceSpec.
Is there a way to simulate a real Project in the testing Framework or preparing multiple files for the same run of the Recipe (as it behaves in the maven plugin)?

**Comment by MBoegers** [comment]
Hi @SilasSchaprian, 
a good way to get direct support is the Open Rewrite Community Slack, but we provide help here as well :)

You can write a test which works on multiple files (like java and xml) like in [ParameterizedRunnerToParameterizedTest](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/test/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterizedTest.java#L527) see https://docs.openrewrite.org/authoring-recipes/recipe-testing for more information.
Or you could publish the [artifact localy](https://docs.openrewrite.org/authoring-recipes/recipe-development-environment#local-publishing-for-testing) and run it against one of your projects.

**Comment by MBoegers** [comment]
Maybe you can add some context and describe your goal a little bit more. Than we can provide a more tailored answer

**Comment by SilasSchaprian** [comment]
Hey @MBoegers thanks for the answer :)

My Problem is that i want to author a recipe that reads a certain key from a config.yml in the project and depending on the value, i have to execute another Recipe with different parameters. So i dont think the ParameterizedRunner will help (if i understood it correctly)

Having a test case for the problem would be cool because the debugger can be helpful while authoring a recipe.

**Comment by MBoegers** [comment]
Okay in this case could define the yaml next to the Java expectation in the rewriteRun method call.

**Comment by SilasSchaprian** [comment]
Thank you! I am going to give it a try :)

**Comment by MBoegers** [comment]
It should look similar to this, sorry I have no IDE at hand. I think you can find everything in this repository and in the rewrite-yaml project. 

If you encounter any further problems feel free to ask 😊

```java
class MyTest implements RewriteTest {
  @Test
  void test(){
    rewriteRun(
      yml("""
       yml: here
       """),
      java("""
       //original Java
       """, """
       //expected Java
       """)
    )
  }
}
```

**Comment by SilasSchaprian** [comment]
Hey @MBoegers i know that this is kind of another question but since i already opened this ticket I thougt it would be okay to aks here..

For my Recipe to work i Need to run a recipe over the whole project before my others are allowed to.

```
@Override
    public List<Recipe> getRecipeList() {
        RecipeA recipeA = new REcipeA();
        return List.of(
                recipeA,
                new RecipeB(recipeA),
                new RecipeC()
        );
    }
```

in ``recipeA`` I have a property I need to access in B.

Is there a way to ensure recipeA was run for the whole Project instead of being run first for the current LST?

I hope my question is understandable

**Comment by MBoegers** [comment]
You can define preconditions in Java recipes as well. To do so just wrap your Visitor instance in the `getVisitor` method. See [AddManagedDependency Line 159](https://github.com/openrewrite/rewrite/blob/702ec676dc218c9998846f908ff9ffbe4cba2c34/rewrite-maven/src/main/java/org/openrewrite/maven/AddManagedDependency.java#L159) for example.

**Comment by knutwannheden** [comment]
It sounds like you may want to have a `ScanningRecipe` which processes all sources in two phases, so that you in the first phase can scan for a certain occurrence and then in the second phase act upon it.

**Comment by SilasSchaprian** [comment]
@knutwannheden @MBoegers awesome i will look into those options. Thank you!!

**Comment by SilasSchaprian** [comment]
@knutwannheden that worked for me.. Thank you!
