### ISSUE TITLE
Assertions.assertThrows static import is not added during Junit 4 to 5 migration

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#55]
When migrating the `spring-cloud-openfeign-core` project from JUnit 4 to 5 the `assertThrows` static import is not **successfully** added to the class.  

~~This is the case even though maybeAddImport is invoked by [ExpectedExceptionToAssertThrows](https://github.com/openrewrite/rewrite-testing-frameworks/blob/502763452dbd970bba2b4c0db633c0a67a48962c/src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java#L125) recipe~~.  

UPDATE: This particular assertThrows is added by `UpdateTestAnnotation`, not `ExpectedExceptionToAssertThrows`.

This task is to figure out why the import is not added and fix the underlying problem

`org.springframework.cloud.openfeign.support.SpringEncoderTests` is the class presenting the issue after rewrite:fix has been applied

**Comment by jkschneider** [comment]
Looks to be dependency related. This fails to add the import only when `EncodeException` is not on the classpath:

```java
package org.springframework.cloud.openfeign.support;

import feign.codec.EncodeException;
import org.junit.Test;

public class SpringEncoderTests {
    @Test(expected = EncodeException.class)
    public void testMultipartFile1() {
        throw new IllegalArgumentException("boom");
    }
}
```

**Comment by pway99** [comment]
an example of where this happens
https://github.com/spring-cloud/spring-cloud-netflix/blob/8eb11b5730953daf53dd7a65286e82e5bda3ce5f/spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/EurekaInstanceConfigBeanTests.java#L160-L164

**Comment by jkschneider** [comment]
`feign-core` is an optional dependency with respect to `spring-cloud-openfeign-core`.
