### ISSUE TITLE
Junit 5 assertThrows should only operate on the last statement rather than wrap the entire method body as lambda

### ISSUE THREAD

**Issue by shivanisky** [openrewrite/rewrite-testing-frameworks#552]
## What problem are you trying to solve?
I have run the Open Rewrite junit 4 to 5 recipe on our codebase. What I'm noticing is with the assertThrows is it wraps the entire method into a lambda for assertThrows. This is then ignoring the feature of junit 5 assertThrows for fine grained verification of a statement throwing an exception.

## Describe the solution you'd like
From my experience, in order to to use the junit 5 features, the best way to do this is to only pass in the last statement into the lambda for assertThrows and use any previous statements as set up statements. However, this causes a problem, that if the last statement isn't the one that generates the exception, then it could cause the test to fail. However, I prefer it this way, as the vast majority of the time, the last statement is the one that generates the exception. Any thoughts?

## Have you considered any alternatives or workarounds?
Not really - please suggest anything here

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?
Yes

**Comment by timtebeek** [comment]
hi @shivanisky ! Thanks for the suggestion and the offer to pick this up. I recall spotting this same pattern and reporting it at what feels like a long time ago, when I was just a community contributor. There's some more discussion around this, and some troublesome edge cases logged here:
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/194

Of course we're a little further since, so perhaps a limited recipe implementation can already convert some simpler cases.

**Comment by timtebeek** [comment]
Would you agree the logged issues are similar enough that it could make sense to close this one as a duplicate?

**Comment by shivanisky** [comment]
Yes I agree - interesting that you raised the same issue 2 years ago. The
older issue has a lot more detailed and valuable conversation. Happy to
continue the discussion in the issue you raised Tim. I do believe that it
may be worth breaking the build for this one as default, or giving the user
an optional recipe to use which could break the build <- I would certainly
pick this recipe. The "do no harm" rule I think should be more of a
guideline, as sometimes not doing harm is more harmful :).
