### ISSUE TITLE
Jmockit Verification with no times should be migrated to atLeastOnce() in Mockito, same for JMockitExpectation with no times or result

### ISSUE THREAD

**Issue by shivanisky** [openrewrite/rewrite-testing-frameworks#553]
## What problem are you trying to solve?
A Jmockit Verification eg:
```
new Verifications() {{
    myObject.wait(anyLong);
}};
```
Should be migrated to in Mockito:
```
verify(myObject, atLeastOnce()).wait(anyLong());
```

Instead it is migrated to:
```
verify(myObject).wait(anyLong()); <-- which matches the invocation exactly one times
```

Which it should not be as per the documentation. It was done the previous way for what the developer intended but it may cause test failures.

https://www.javadoc.io/doc/org.jmockit/jmockit/latest/mockit/Verifications.html
"By default, **at least one** matching invocation must be found for the verification to be successful; if no matching invocations are found, an assertion error is thrown."

## Have you considered any alternatives or workarounds?
Yes - would like feedback on what people prefer, to have test failures and then migrate them to mockito with the exact times or to not have test failures and do an exact migration of JMockit Verifications. I'm leaning towards the latter.

## Additional context
Same issue is for JMockit Expectations with no times or result, which get migrated to the above verify

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?
Yes - almost done with code changes, but want to make sure that this is the right thing.

Inviting @tinder-dthomson and @timtebeek  for comments

**Comment by timtebeek** [comment]
Intuitively I'd say things could get rather noisy if we convert every case to atLeastOnce, even if technically more correct. I'd consider it perhaps an implementation issue with the code under test if it repeatedly calls the same mocked method. In practice it could be enough to let folks introduce atLeastOnce for failing tests as part of completing the migration, as otherwise folks reading any other test might conclude the wrong behavior, or usage patterns for Mockito.

Curious to hear @tinder-dthomson thoughts as well.

**Comment by shivanisky** [comment]
Yes it's getting noisy, even in the test cases:

```
      myObject.wait(1L);
      myObject.wait();
      new Verifications() {{
             myObject.wait(anyLong);
             myObject.wait();
      }};
}
```
```
      myObject.wait(1L);
      myObject.wait();
      verify(myObject, atLeastOnce()).wait(anyLong());
      verify(myObject, atLeastOnce()).wait();

```

I was just getting annoyed at the test failures I saw and having to fix every one up. But ... I'm happy to stick with the way it is currently which is what I thought was best at the time.

**Comment by shivanisky** [comment]
I sort of disagree, but I am ok to agree to disagree :). Funny thing is that this was my original intention, to go with the developer's probable intention, rather than a perfect translation. In an ideal world, that's best, but with deadlines and as I am migrated hundreds of tests, seeing these failures has been a bit of a pain. I won't be using the code changes suggested in this issue anyway, as almost done with the migration. But, thought to prevent others from going through similar pain. However, still, happy to go with what you suggest :)

Also couldn't get to the junit 5 stuff, due to flu and have had to take time off my regular work. Perhaps this week, can work on it.

**Comment by tinder-dthomson** [comment]
> Intuitively I'd say things could get rather noisy if we convert every case to atLeastOnce, even if technically more correct. I'd consider it perhaps an implementation issue with the code under test if it repeatedly calls the same mocked method. In practice it could be enough to let folks introduce atLeastOnce for failing tests as part of completing the migration, as otherwise folks reading any other test might conclude the wrong behavior, or usage patterns for Mockito.
> 
> Curious to hear @tinder-dthomson thoughts as well.

I have to concur with this assessment. I don't think most developers expect `atLeastOnce` to be in every verification, and in fact the default behavior is more strict. For test cases where `atLeastOnce` is actually necessary, I suspect this will help push to make some of those tests more strict (i.e. by using `times` instead), unless there is a mock invocation in a dynamic loop (which isn't out of the realm of possibility but also not something I've seen).

Just as a datapoint, in our migration we had _zero_ instances where `atLeastOnce` was necessary, and this was thousands upon thousands of test cases. So this will vary widely depending on the organization.

**Comment by shivanisky** [comment]
Thanks ... for inputs and I guess majority doesn't want atLeastOnce as default verification. Fair enough.

Past Shivani > Current Shivani 😀

In 90%-100% of cases atLeastOnce is useless. Why change the 90% for the 5-10%. Fair enough.
