### ISSUE TITLE
Remove hamcrest-junit dependency in Junit4to5Migration recipe

### ISSUE THREAD

**Issue by FieteO** [openrewrite/rewrite-testing-frameworks#575]
## What version of OpenRewrite are you using?

2.16.0

## How are you running OpenRewrite?

I am applying the Maven Command Line command on a single module project.

## Can you share your configuration so that we can rule out any configuration issues?
I am not explicitly changing any configuration.

## What is the smallest, simplest way to reproduce the problem?

```xml
<dependency>
	<groupId>org.hamcrest</groupId>
	<artifactId>hamcrest-junit</artifactId>
	<scope>test</scope>
</dependency>
```

## What did you expect to see?

Dependency removed.

## What did you see instead?

Dependency still declared.
```xml
<dependency>
	<groupId>org.hamcrest</groupId>
	<artifactId>hamcrest-junit</artifactId>
	<scope>test</scope>
</dependency>
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
yes

**Comment by timtebeek** [comment]
Thanks for logging this separately. As indicated this could be as simple as copying these lines:
https://github.com/openrewrite/rewrite-testing-frameworks/blob/05c20949d0534d58de4c3714f077bab2a0923f74/src/main/resources/META-INF/rewrite/junit5.yml#L112-L114

Might be good to double check if any replacement should be added, and in which cases, but you'll know more from your experience in migrating there.

**Comment by timtebeek** [comment]
- Fixed in https://github.com/openrewrite/rewrite-testing-frameworks/pull/577
