### ISSUE TITLE
JUnit4 -> JUnit5 migration does not respect junit4's scope

### ISSUE THREAD

**Issue by crankydillo** [openrewrite/rewrite-testing-frameworks#585]
We have test libraries that have compile-scoped dependencies on junit4 libraries.  We'd like to run the migration on these, but I believe the current solution assumes the junit4 dependencies will have test scope.

## What version of OpenRewrite are you using?

- OpenRewrite v(whatever you get with maven plugin)
- Maven/Gradle plugin v5.39.0
- rewrite-testing-frameworks module_ v2.16.0

## How are you running OpenRewrite?

Maven

**Comment by timtebeek** [comment]
We indeed had up to now assumed the `scope: test` when adding the replacement JUnit Jupiter dependency:
https://github.com/openrewrite/rewrite-testing-frameworks/blob/17b0427564e5fa1d56b29f96469b7aea8c672210/src/main/java/org/openrewrite/java/testing/junit5/AddJupiterDependencies.java#L82-L86

I think that's a reasonable assumption to make, and would only break for projects that indeed use JUnit in src/main instead.

There is one option to pass in a scope of `null` instead, which should then look at where the `onlyIfUsing: "org.junit..*"` matches are used. 🤔

**Comment by timtebeek** [comment]
- Fixed in https://github.com/openrewrite/rewrite-testing-frameworks/pull/586

**Comment by timtebeek** [comment]
Closed with the presumed fix in #586; if that does not show improvement there then I'd need to know which recipes you ran, and which recipes made incorrect changes, or failed to make changes. That wasn't immediately clear from your outline above. :)

**Comment by crankydillo** [comment]
> There is one option to pass in a scope of `null` instead, which should then look at where the `onlyIfUsing: "org.junit..*"` matches are used. 🤔

Ah, I didn't know `AddDependency` worked this way!  I did a quick glance and thought a fix might be difficult:)

**Comment by crankydillo** [comment]
> Closed with the presumed fix in #586; if that does not show improvement there then I'd need to know which recipes you ran, and which recipes made incorrect changes, or failed to make changes. That wasn't immediately clear from your outline above. :)

Sorry about that, I was using `org.openrewrite.java.testing.junit5.JUnit4to5Migration` from 2.16.0.
