### ISSUE TITLE
JUnit migration recipe for TestRule, TestWatcher, and Description

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#60]
import org.junit.Rule;
import org.junit.rules.TestRule;
import org.junit.rules.TestWatcher;
import org.junit.runner.Description;

Antlr4:
https://github.com/antlr/antlr4/blob/c2f104cd0810fa2e09a44f8030d1e54c135a20c2/antlr4-maven-plugin/src/test/java/org/antlr/mojo/antlr4/Antlr4MojoTest.java#L35-L38

Thingsboard
https://github.com/thingsboard/thingsboard/blob/1d2918f0a134f0dcd525c2581ad8afe1ac26e6ac/msa/black-box-tests/src/test/java/org/thingsboard/server/msa/AbstractContainerTest.java#L41-L44

**Comment by sambsnyd** [comment]
There's no generic, one-size-fits-all solution for Rule/TestRule/TestWatcher. They're generic extensibility mechanisms. So each way they are implemented in practice has to be handled individually.
