### ISSUE TITLE
org.junit.Assert#assertThat => org.hamcrest.MatcherAssert#assertThat

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#63]
`java: a type with the same simple name is already defined by the single-type-import of org.assertj.core.api.Assertions`
```
import org.junit.jupiter.api.Assertions;
import static org.junit.jupiter.api.Assertions.assertThat;
```
discovered while testing rewrite-testing frameworks on 
https://github.com/estatio/estatio/blob/001eecddf1381c2ff35c4f7457b3a4b435801478/estatioapp/app/src/test/java/org/estatio/module/lease/integtests/invoicing/Invoice_IntegTest.java#L78-L80

**Comment by jkschneider** [comment]
I'm not sure about the original premise of this issue. It seems like `assertThat` has been removed in JUnit5. It was deprecated in JUnit4, asking to migrate to the Hamcrest equivalent instead.
