### ISSUE TITLE
JMock for Junit 5

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#64]
While testing estatio a JUnit 4 `@Rule` using `JUnitRuleMockery2` was discovered.
consider a recipe for this rule conversion to support testing

https://github.com/estatio/estatio/blob/001eecddf1381c2ff35c4f7457b3a4b435801478/estatioapp/app/src/test/java/org/incode/module/document/dom/impl/docs/DocumentAbstract_Test.java#L16-L17

https://mvnrepository.com/artifact/org.jmock/jmock-junit5

**Comment by sambsnyd** [comment]
This seems pretty uncommon. Didn't find the type in any of the 77 repositories we've currently ingested. I don't think it's worth investing in at the moment.
