### ISSUE TITLE
"MigrateHamcrestToAssertJ" recipe does not fully migrate `comparesEqualTo` matcher

### ISSUE THREAD

**Issue by jtama** [openrewrite/rewrite-testing-frameworks#647]
## What version of OpenRewrite are you using?
I am using

- OpenRewrite v2.22.0
- Maven/Gradle plugin ?
- rewrite-testing-frameworks v2.22.0

## How are you running OpenRewrite?

I am using executing openrewrite through the shell, and my project is a single module project.
```shell
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.testing.junit5.JUnit4to5Migration,org.openrewrite.java.testing.assertj.Assertj -Drewrite.exportDatatables=true
```

## What is the smallest, simplest way to reproduce the problem?
```java
import java.math.BigDecimal;
import static org.hamcrest.Matchers.comparesEqualTo;

public class DummyTest {

    @Test
    public void dummyTest() {
        assertThat(new BigDecimal("2"), comparesEqualTo(new BigDecimal("2.0")));
    }
}
```

## What did you expect to see?

```java
import java.math.BigDecimal;
import static org.assertj.core.api.Assertions.assertThat;

public class DummyTest {

    @Test
    public void dummyTest() {
        assertThat(new BigDecimal("2")).isEqualByComparingTo(new BigDecimal("2.0"));
    }
}

```

## What did you see instead?
```java
import java.math.BigDecimal;
import static org.hamcrest.Matchers.comparesEqualTo;

public class DummyTest {

    @Test
    public void dummyTest() {
        assertThat(new BigDecimal("2"), comparesEqualTo(new BigDecimal("2.0")));
    }
}
```

I think it's all linked to to this line https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/resources/META-INF/rewrite/hamcrest.yml#L65 that limits the type argument to `String`.

I can provide a PR if you like.

**Comment by timtebeek** [comment]
Hi @jtama ; thanks for calling that out! We had indeed added that quick limit to String type following
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/468
- https://github.com/openrewrite/rewrite-testing-frameworks/pull/469

I hadn't since taken the time to reevaluate which other types are fine to support there as well; I'd welcome a PR that adds a few more allowed types to be converted, thanks!

**Comment by jtama** [comment]
Ok I'll do that.

**Comment by jtama** [comment]
Ok I tried very hard to reproduce the behaviour but never succeded, the recipe does exists, the unit test pass. And we reran the MigrateHamcrestToAssertJ recipe the project on which we had the issue, and everything is has expected. Sorry for false issue.
