### ISSUE TITLE
JUnit 4 ClassPathSuite runner recipe

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#66]
Recipe for converting ClassPathSuite to its associated JUnit 5 variant
discovered while testing ThingsBoard 
https://github.com/thingsboard/thingsboard/blob/2bd28cb021bc794db5c297cae5063362bee61427/msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ContainerTestSuite.java#L33-L34

**Comment by jkschneider** [comment]
Support for this was added very recently, not in a GA release of JUnit 5 yet. See https://github.com/junit-team/junit5/pull/2416.

**Comment by sambsnyd** [comment]
We can reopen this in the future when there's a GA of JUnit 5 containing this
