### ISSUE TITLE
JUnit 4 to 5 migration recipe for  ExternalResource

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#69]
Discovered while testing: 
https://github.com/thingsboard/thingsboard/blob/1dc47b5cc56f1f10e0ce7c3f0d2b60e34b83393c/msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ThingsBoardDbInstaller.java#L18-L27

ExternalResourceSupport is the JUnit 5 variant:
https://junit.org/junit5/docs/5.0.0-M4/api/org/junit/jupiter/migrationsupport/rules/ExternalResourceSupport.html

**Comment by sambsnyd** [comment]
We've got a few hits on this, could be worth pursuing since there's an existent JUnit 5 analogue 
![image](https://user-images.githubusercontent.com/8549033/122488408-45505700-cf92-11eb-8386-e49f3254057e.png)

**Comment by pway99** [comment]
This transformation requires either using the `jupiter-migration-support` library or building a custom Junit Jupiter Extension.  Closing this issue due to the potential complexity and a limited number of use cases.
