### ISSUE TITLE
JUnit4 TestContainers migration recipe

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#75]
[Testcontainers](https://www.testcontainers.org/)

> Testcontainers is a Java library that supports JUnit tests, providing lightweight, throwaway instances of common databases, Selenium web browsers, or anything else that can run in a Docker container.

[spring-cloud-consul  ConsulTestcontainers](https://github.com/spring-cloud/spring-cloud-consul/blob/2bd5282ecd1a391f217999c23bcd83e89e65ce80/spring-cloud-consul-core/src/test/java/org/springframework/cloud/consul/test/ConsulTestcontainers.java#L38-L41) requires a [JUnit 5 Testcontainers](https://www.testcontainers.org/test_framework_integration/junit_5/) migration recipe

[spring-batch MySQLJdbcJobRepositoryTests](https://github.com/spring-projects/spring-batch/blob/11bac7c4e1903553a1e3b7411efc56dadd59234a/spring-batch-core/src/test/java/org/springframework/batch/core/test/repository/MySQLJdbcJobRepositoryTests.java#L62-L63) uses a [MySQLContainer](https://www.testcontainers.org/modules/databases/mysql/)

**Comment by tkvangorder** [comment]
More details on this: 

The `org.testcontainers:testcontainers` library has a transitive dependency on JUnit 4 and therefore, we cannot exclude junit 4 from this specific library.  Support for JUnit 5 is enabled via a second artifact, `org.testcontainers:junit-jupiter` 

See these two links for details on JUnit 5 support: 

https://www.testcontainers.org/test_framework_integration/junit_5
https://www.testcontainers.org/quickstart/junit_5_quickstart/

This task will require: 

- Modifying the rule that excludes JUnit 4 from all dependencies (such that it does not exclude the transitive dependency for `org.testcontainers:testcontainers`)
- Adding the additional `org.testcontainers:junit-jupiter` library.
- Replacing the user of `@Rule` with `@Container` and adding the `@Testcontainers` annotation to those tests that are using test containers

**Comment by sambsnyd** [comment]
This is a good idea but I don't believe it will be a priority for us in the near term unless we have someone asking for it.
