### ISSUE TITLE
JUnit 4 to 5 junit.framework.TestCase migration recipe

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#78]
Discovered while testing `Boot2JUnit4to5Migration` on spring-batch.
This task is to implement a new migration recipe for `junit.framework.TestCase` test classes.

e.g. [MapJobRecistryTests](https://github.com/spring-projects/spring-batch/blob/11bac7c4e1903553a1e3b7411efc56dadd59234a/spring-batch-core/src/test/java/org/springframework/batch/core/configuration/support/MapJobRegistryTests.java#L31) and [JdbcJobDaoQueryTests](https://github.com/spring-projects/spring-batch/blob/5c57ed47b8be4b3419229f0617cba895610ab9bc/spring-batch-core/src/test/java/org/springframework/batch/core/repository/dao/JdbcJobDaoQueryTests.java#L34) instances of [TestCase](https://github.com/junit-team/junit4/blob/main/src/main/java/junit/framework/TestCase.java)

Jetbrains [blog](https://blog.jetbrains.com/idea/2020/08/migrating-from-junit-4-to-junit-5/) on converting TestCase
javaprepare blog [Junit-3 TestCase](http://javaprepare.blogspot.com/2008/06/junit-3.html)

Recipe Process:
1. Remove TestCase extension
2. Add `@Before` annotation to `setUp()` method declaration
3. Add `@After` annotation to `tearDown()` method declaration
4. Add `@Test` annotation to `test...()` method declarations
5. Convert `TestCase` assertions to `Assert` assertions
6. Fix imports

Before:
```java
import junit.framework.TestCase;
public class MathTest extends TestCase {
    protected double fValue1;
    protected double fValue2;

    protected void setUp() {
        fValue1= 2.0;
        fValue2= 3.0;
    }
    
    public void testAdd() {
        double result= fValue1 + fValue2;
        assertTrue(result == 5.0);
    }

    protected void tearDown() throws Exception {
        fValue1 = 0.0;
        fValue2 = 0.0;
    }
}
```
After:
```java
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class MathTest {
    protected double fValue1;
    protected double fValue2;

    @Before
    public void setUp() {
        fValue1= 2.0;
        fValue2= 3.0;
    }

    @Test
    public void testAdd() {
        double result= fValue1 + fValue2;
        Assert.assertTrue(result == 5.0);
    }

    @After
    public void tearDown() throws Exception {
        fValue1 = 0.0;
        fValue2 = 0.0;
    }
}
```

**Comment by okundzich** [comment]
Investigate how hard this is.
