### ISSUE TITLE
JUnit 4 to 5 MethodRule recipe

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#83]
Discovered while testing `Boot2Junit4to5Migration`on `spring-batch`

spring-batch [PollingAsyncItemProcessorMessagingGatewayTests](https://github.com/spring-projects/spring-batch/blob/11bac7c4e1903553a1e3b7411efc56dadd59234a/spring-batch-integration/src/test/java/org/springframework/batch/integration/async/PollingAsyncItemProcessorMessagingGatewayTests.java#L54-L77) MethodRule implementation

```java
@Rule
public MethodRule rule = new MethodRule() {
	public Statement apply(final Statement base, FrameworkMethod method, Object target) {
		return new Statement() {
			@Override
			public void evaluate() throws Throwable {
				StepScopeTestUtils.doInStepScope(stepExecution, new Callable<Void>() {
					public Void call() throws Exception {
						try {
							base.evaluate();
						}
						catch (Exception e) {
							throw e;
						}
						catch (Throwable e) {
							throw new Error(e);
						}
						return null;
					}
				});
			};
		};
	}
};
```

**Comment by sambsnyd** [comment]
`MethodRule` can be implemented & extended any number of ways. I doubt there could exist a refactoring recipe that accounts for all possible `MethodRule` implementations. Especially since the JUnit 5 extensibility mechanisms that supplanted Rules work in a fundamentally different way.
