### ISSUE TITLE
JUnit 4 to 5 migration  ComparisonFailure recipe

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#84]
Discovered while testing Boot2Junit4to5Migrationon spring-batch

[ComparisonFailure](https://junit.org/junit4/javadoc/latest/org/junit/ComparisonFailure.html) extends `AssertionError`
> Thrown when an assertEquals(String, String) fails. Create and throw a ComparisonFailure manually if you want to show users the difference between two complex strings. 

spring-batch [AssertFileTests](https://github.com/spring-projects/spring-batch/blob/11bac7c4e1903553a1e3b7411efc56dadd59234a/spring-batch-test/src/test/java/org/springframework/batch/test/AssertFileTests.java#L39-L48) catching `org.junit.ComparisonFailure`

**Comment by sambsnyd** [comment]
This is a niche enough feature of JUnit that I don't think we'll be investing in this unless someone is asking for it. Feel free to reopen if you are going to work on this.
