### ISSUE TITLE
Mockito Matchers to ArgumentMatchers

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-testing-frameworks#87]
discovered while applying Boot2JUnit4to5Migration to [spring-cloud-shell](https://github.com/spring-projects/spring-shell)

Mockito [Matchers](https://www.javadoc.io/static/org.mockito/mockito-core/2.21.0/org/mockito/Matchers.html) is deprecated and replaced by [ArgumentMatchers](https://www.javadoc.io/static/org.mockito/mockito-core/2.21.0/org/mockito/ArgumentMatchers.html) 

found in spring-cloud-shell [ShellTest](https://github.com/spring-projects/spring-shell/blob/296db93462eac8a9d6b10009a2e3f7b9fe22f5ad/spring-shell-core/src/test/java/org/springframework/shell/ShellTest.java#L38-L39)

This looks like a simple ChangeType declarative recipe and possible Upgrade mockito version 
```java
/**
 * @deprecated Use {@link ArgumentMatchers}. This class is now deprecated in order to avoid a name clash with Hamcrest
 * <code>org.hamcrest.Matchers</code> class. This class will likely be removed in version 3.0.
 */
@Deprecated
public class Matchers extends ArgumentMatchers {
}
```

**Comment by sambsnyd** [comment]
This is already part of the Mockito migration. I think it was actually one of the very first things to be part of it. 
I'm willing to bet this not working when run on the saas had something to do with the test sources classpath issues that were fixed yesterday. Feel free to reopen and investigate as a bug if you see this reproduce again.
